return {
    unitName = "control_range_extender",
    unitDisplayName = "Control Node",
    unitTooltip = "- Can be <color=#00ffff>placed outside</color> your <color=green>build area</color>.\n(Blue circle must overlap with green tiles)",
    unitBlurb = "Build Area Extender",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "X",
    picture = "1_12011_control_range_extender.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012011,
        factionID = 101,
        macroType = "TRUE",
        cost_matter = 80,
        cost_energy = 100,
        cost_supply = 0,
        cost_time = 30,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "Command and Control is a difficult thing to handle even in a clear exospacial battlefield. But in the Spance it is a nightmare.\n\nThe Local Base Control Node, (LBCN) works as a dedicated command relay.  Hardlinked to it's owner's control grid, and networked to all surrounding buildings with extremely powerful comms systems. It distributes commands, handles reports from local systems, and coordinates material logistics.\n\nThe LBCN contains a rather hefty Base Core specifically dedicated to platform commander neural mirroring, allowing it to somewhat assume what you want at any given time. Often allowing it to reject hostile attempts to hack control and preallocate resources to as-of-yet-ungiven construction tasks.\n\nFinally, it also houses a set of construction drone bays and fleets of logistics haulers that work tirelessly to shift materials around a platform base.",
    },
    scale = 2,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_structure_range_extender/01_structure_range_extender",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "unitBubble(Clone)",
            mesh = "01_aegis_icosphere/01_aegis_icosphere",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.1, 1.1, 1.1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_structure_range_extender/01_structure_range_extender",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
    },
    unitCore = true,
    sphereCollider = {
        center = { 0, 0, 0 },
        radius = 0.5,
        isTrigger = false,
    },
    health = {
        unitClass = "HEAVY",
        health = 2500,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 15,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 2,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "EXTENDER",
        ring = { 0, 0 },
        rectangle = { 2, 2 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = true,
    influence = {
        strength = { 5, 1 },
        ring = { 0, 7 },
        rectangle = { 0, 0 },
        matrixDimensions = { 0, 0 },
    },
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 3,
    },
}
