return {
    unitName = "turret_repair",
    unitDisplayName = "Repair Turret",
    unitTooltip = "",
    unitBlurb = "Health repair turret.",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "R",
    picture = "1_12018_turret_repair.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012018,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 20,
        cost_energy = 10,
        cost_supply = 2,
        cost_time = 15,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Hull Repair</color>\nDesigned to support turrets.\n- Repairs Health / Armour of allies.\n- Prioritizes heavily damaged structures.",
        description = "- - -\nInfo:\n\nThe R2015 Reassembler is a form of point-shadow weapon. Amusingly, the Dauwn assault light employs a similar system to shatter target armour. However, with a bit of gamma-void agitation, one can cause hardened materials to strengthen rather than shatter. With the addition of new materials, holes can be patched and armour reinstated.",
        weaponInfo = {
            { 1015020, 1, 0 },
        },
    },
    scale = 1,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    displayAreaRadius = 8,
    displayAreaColour = { 0.298039, 1, 0.768628, 0.25098 },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_turret_repair/01_structure_turret_repair",
    materials = { "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_teamColour" },
    parts = {
        {
            name = "turret_beam",
            position = { 0, 0.356, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.7, 0.7, 0.7 },
            weapon = {
                weaponID = 1015020,
                turnSpeed = 114.5916,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 90,
                    down = 35,
                },
            },
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.12015, 0.12015, 0.12015 },
                    weaponVisualConfig = {
                        laserColour = { 0.554529, 1, 0.447059, 1 },
                        intensity = 3,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "turretModel",
                    mesh = "01_light_repair/01_turret_repair",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_Glow_Heal" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "turretbody",
                    mesh = "01_light_repair/01_turret_repair_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_turret_repair_aegis/01_structure_pulseCannon_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_small",
            mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
            materials = { "01_MT_BaseColour_structure_primary" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "glow",
                    mesh = "01_turret_repair/01_structure_turret_repair",
                    materials = { "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    parts = {
                        {
                            name = "turretModel (1)",
                            mesh = "01_light_repair/01_turret_repair",
                            materials = { "01_MT_buildglow_1", "01_MT_buildglow_1" },
                            position = { 0, 0.356003, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.7, 0.7, 0.7 },
                        },
                        {
                            name = "turretbody (1)",
                            mesh = "01_light_repair/01_turret_repair_body",
                            materials = { "01_MT_buildglow_1" },
                            position = { 0, 0.356003, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.7, 0.7, 0.7 },
                            turretBody = true,
                        },
                    },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 1, 0.5, 1 },
        orientation = { 0, 0, 0 },
        bevelRadius = 0.2,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "MEDIUM",
        health = 500,
        health_regen_per_second = 3,
        max_regen_frac = 0,
        armour = 10,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 1.5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 1.2,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013021,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "DEFENCE",
        ring = { 0, 0 },
        rectangle = { 1, 1 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 2,
    },
}
