return {
    unitName = "storage_matter",
    unitDisplayName = "Matter Silo",
    unitTooltip = "",
    unitBlurb = "Matter storage structure.",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "M",
    picture = "1_12024_storage_matter.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012024,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 5,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 10,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "<color=yellow>Tactical:</color>\n- Stores matter.\n- Makes you question your life's choices in selecting this unit's databank entry for lore.\n\nSeriously it stores matter. It's a big bin in space. Are you truely this starved for LORE? Sure it's got like conveyors and stuff, and like little bays for delivery drones. How am I supposed to make this entertaining? I suppose it is a \"skill issue\" on my part, as the kids say. Okay fine. You want lore? Here's your lore.\n\n\nThe MS1 generalised materials and resource consignment facility is the cornerstone of spancial resource handling. Integrated into nearly every Platform in the Kontaalen Armada. \n\nGravitationally partitioned spances (a reminder that spance, means a 3d span, or polygonal volume) are utilised for truly dynamic material storage. There are no solid parts, or complex handling systems needed what so ever. The system is purely handled via gravitational field manipulation at a very very minor scale - after all most materials are innert. You don't need much to make them just sit in a corner.\n\nAs such the MS1 has both impressed, and somewhat aggitated members of the exo-spancial community for being... shall we say... \"surprisingly dangerous\". You see, if you have a large box full of rocks and your gravity handling goes haywire, you can end up with what experts like to call a \"freaking rock bomb\" sending materials out across your operational area.\n\nIt also makes a really nice parking garage for ships because you can have parking spaces and \"walls\" made out of GRAVITY. Quite safe, and doesn't damage a vehicle. Normally.",
    },
    scale = 1,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "structure_storage_matter/01_structure_storage_matter",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "unitBubble(Clone)",
            mesh = "structure_storage_matter/01_structure_storage_matter",
            materials = { "01_MT_Aegis", "01_MT_Aegis", "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.1, 1.1, 1.1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_small",
            mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
            materials = { "01_MT_BaseColour_structure_primary" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "glow",
                    mesh = "structure_storage_matter/01_structure_storage_matter",
                    materials = { "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
    },
    unitCore = true,
    boxCollider = {
        center = { 0, 0, 0 },
        size = { 0.9, 0.9, 0.9 },
        isTrigger = false,
    },
    health = {
        unitClass = "LIGHT",
        health = 500,
        health_regen_per_second = 2,
        max_regen_frac = 0,
        armour = 2,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0.5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = true,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013020,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "ECONOMY",
        ring = { 0, 0 },
        rectangle = { 1, 1 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = true,
    resourceCapacity = {
        matter = 50,
        energy = 0,
        phase = 0,
        logistics = 0,
    },
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 1,
    },
}
