return {
    unitName = "special_testerPlatform",
    unitDisplayName = "Ripper Projector",
    unitTooltip = "THIS IS NOT FOR YOU",
    unitBlurb = "Wide Area Ripper Field",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_12032_special_testerPlatform.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012032,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 50,
        cost_energy = 100,
        cost_supply = 10,
        cost_time = 30,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "HIDDEN",
        requiredLevelForVisible = "9898",
        requiredLevelForDescription = "",
        tactical = "",
        description = "<color=yellow>Tacticall:</color>\n+ Highly expensive, anti-missile defence shield projector.\n\n\nInfo:\n\nThe KADO-09 experimental projected shadow-point field system, is often found at facilities in extreme danger of asteroid rain. It has likewise found it's place in anti-missile defence systems.\n\nFleetsoul Hebren's development division took little known properties of Kontaal's Shadow-Point manipulation technology, mixed with common Warp Drive engines. The result devised is a field projection system that uses the fabric of reality ( to a limited extent ). Effectively, it creates a small area of pinched space time that can absorb incoming kinetic force and energy.",
        weaponInfo = {
            { 1015058, 1, 0 },
        },
    },
    scale = 2,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    displayAreaRadius = 11,
    displayAreaColour = { 1, 0, 0, 0.25098 },
    inEditor = false,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_civ_1x1_04/01_civ_1x1_04",
    materials = { "01_MT_BaseColour_teamColour", "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "turret_beam",
            position = { 0, 0.5, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015058,
                turnSpeed = 229.1831,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "shield",
                    position = { 0, 0, 1 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    autoModule = {
                        moduleTypeID = 26001,
                        reportKillsToParent = false,
                        doDamageToEntityOnDeath = false,
                    },
                },
                {
                    name = "turretModel (1)",
                    mesh = "unity default resources/Cube",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0.5 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.2, 0.2, 1 },
                },
            },
        },
    },
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Sphere",
        center = { 0, 0, 0 },
        radius = 0.5,
        orientation = { 0, 0, 0 },
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "HEAVY",
        health = 3000,
        health_regen_per_second = 10,
        max_regen_frac = 0,
        armour = 20,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "DEFENCE",
        ring = { 0, 0 },
        rectangle = { 2, 2 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 2,
    },
}
