return {
    unitName = "3x3_turret_missile",
    unitDisplayName = "Rocket Howler",
    unitTooltip = "",
    unitBlurb = "Rocket launching fleet pounder",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "V",
    picture = "1_12033_3x3_turret_missile.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012033,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 250,
        cost_energy = 100,
        cost_supply = 0,
        cost_time = 30,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Anti-Heavy Turret</color>\nDesigned to punish Heavies without PD support.\n- Strong against Heavies / Mediums.\n- Decent against everything.\n- Poor weapon accuracy.",
        description = "At the intersection of targeted munitions and tactical nukes, resides the land of medium ranged missiles. The Howler is designed to deliver substantial payloads to high value heavy targets within the local battlefield - while retaining a degree of efficacy against medium forces.",
        weaponInfo = {
            { 1015067, 1, 1015068 },
        },
    },
    scale = 3,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    displayAreaRadius = 30,
    displayAreaColour = { 1, 0, 0, 0.184314 },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_turret_rocketHowler/01_turretbase_rocketHowler",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "turret",
            position = { 0, 0.2, 0 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015067,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "firingpoint",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_turretbase_pulseHowitser_aegis/01_turretbase_pulseHowitser_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, -0.001, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.771893, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_turret_rocketHowler/01_turretbase_rocketHowler",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, 0.001296, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1.295516, 1 },
                },
            },
        },
        {
            name = "Collider",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            physicsShape = {
                shapeType = "Box",
                center = { 0, 0, 0 },
                size = { 1, 0.677346, 1 },
                orientation = { 0, 0, 0 },
                bevelRadius = 0.89,
                collisionResponse = "None",
                belongsTo = 4294967295,
                collidesWith = 4294967295,
                customTags = 0,
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "None",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 1,
        worldIndex = 0,
        customTags = 0,
    },
    health = {
        unitClass = "CAPITAL",
        health = 5000,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 40,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 3,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 1.2,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "DEFENCE",
        ring = { 0, 0 },
        rectangle = { 3, 3 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
