return {
    unitName = "yard_medium",
    unitDisplayName = "Yard M4",
    unitTooltip = "",
    unitBlurb = "Medium Shipyard",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "F",
    picture = "1_12006_yard_medium.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012006,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 40,
        cost_energy = 10,
        cost_supply = 2,
        cost_time = 15,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "- - -\n\nThe Mk17 Yard M4's fabrication array and cohension deck can produce the entirety of Kontaal's 100m medium vessel schematics - whether exotic or normal - in times unmatched by any counterpart.\n\nAfter the Yard L1, the obvious need to scale up the system to produce more significant forces lead to the M4. Although nearly identical, the M4 was the prototype for magnetic fabrication stabilisation. Allowing the production of larger vessels, despite the increasing weight and unweildyness of the now 100m long vessels.",
    },
    scale = 2,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_yard_medium/01_yard_medium",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "Vortex Cohesion Deck",
            mesh = "vortex Dome/vortex_dome_shell",
            materials = { "mt_vortex_dome_shell_cohesionDeck" },
            position = { 0, 0.1177, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.74767, -0.245864, 0.74767 },
            vortex = true,
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_yard_medium_aegis/01_yard_medium_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.5, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_yard_medium/01_yard_medium",
                    materials = { "01_MT_buildglow_4", "01_MT_buildglow_4", "01_MT_buildglow_4" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 2, 1 },
                },
            },
        },
        {
            name = "Spawnpoint",
            position = { 0, 0.0742, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            spawnerSpawnPoint = {
                code = 0,
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 1, 0.35, 1 },
        orientation = { 0, 0, 0 },
        bevelRadius = 1,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "HEAVY",
        health = 2500,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 5,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 2,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "PRODUCTION",
        ring = { 0, 0 },
        rectangle = { 2, 2 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = true,
    spawner = {
        spawnOffset = { 0, 3, 0 },
        spawnOffsetHeightRandomisation = 1,
        endRotationUseStructureForward = false,
        noUnitGhost = false,
        usesToSelfdestruct = 0,
        simultaniousUnitLimit = 0,
        arrivalData = {
            type = "ARRIVE",
            arrivalDuration = 3,
            approachSpeed = 0.2,
            keepDisabled = false,
        },
    },
    spawnerCapacity = {
        current = 0,
    },
    spawnItems = {
        {
            id = 1011005,
            spawnTime = 30,
            spawnTimeStart = 30,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011023,
            spawnTime = 30,
            spawnTimeStart = 30,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011002,
            spawnTime = 30,
            spawnTimeStart = 30,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011012,
            spawnTime = 30,
            spawnTimeStart = 30,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011024,
            spawnTime = 30,
            spawnTimeStart = 30,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011013,
            spawnTime = 60,
            spawnTimeStart = 60,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
    },
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
