return {
    unitName = "missile_kontaalagrad",
    unitDisplayName = "Kontaalagrad",
    unitTooltip = "",
    unitBlurb = "Strategic Fleet Destroyer",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_14001_missile_kontaalagrad.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1014001,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "DISCOVER",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Anti-Platform Nuke</color>\n- Targets Platforms / Capitals / Extenders.\n- Devastatingly large explosion.\n- Targetable by everything.\n- Vulnerable to sufficient firepower.",
        description = "- - -\nKONTAAL AGRAD\nHome Redeemer\n\nThe singular most devestating weapon a Fleetmarshal can put to use.\n\nThough not an immediate win, the Agrad will utterly devestate opponents that are not ready for it. Dedicated point defence coverage or sufficient laser based weapon systems are required to gun down the surprisingly hardy tactical missile. However it's vast explosion area will likely cause notable damage even if intercepted.\n\n\"Nuke\" once refered to the employment of nuclear-fission based atom-splitter weapons. Generally refered to in dirty terms as \"Atomics\". However in modern times the term nuke has come to encompass all forms of wide area explosive weaponry. \n\nThe G4000 Photonsplitter Tactical Nuke \"Kontaalagrad\" employs photon chisseling to achieve it's impressive blast area. The application of near perfect field impacts and minor space-time warping allows for the shattering of base particles. Resulting in a truely terrifying explosion - relative to how tiny it's payload is.\n\nAny reports of spatio-temporal anomalies resulting from photon chisseling are to be ignored as nothing but imaginative fearmongering. Numerous white-paper reports have discarded such accusations and have gauranteed to our Armadasoul that there are almost zero negative effects.",
        weaponInfo = {
            { -1, -1, -1 },
            { 1015036, 1, 0 },
        },
    },
    scale = 1.5,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_missile_kontalagrad/01_missile_kontalagrad",
    materials = { "01_MT_BaseColour_teamColour", "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "thruster_glow",
            position = { 0, 0, -0.435 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            thruster = {
                decayTime = 0.5,
                workWhenThrustWithinAngleDegrees = 63,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "MT_ThrusterGlow" },
                    position = { 0, 0, -0.176 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.360897, 0.360897, 0.742401 },
                },
                {
                    name = "glow (1)",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "MT_ThrusterGlow" },
                    position = { 0, 0.139, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.055977, 0.212564, 0.475515 },
                },
                {
                    name = "glow (2)",
                    mesh = "thrusterplume/thruster_plume",
                    materials = { "MT_ThrusterGlow" },
                    position = { -0.12, -0.07, 0 },
                    rotation = { 0, 0, 120 },
                    scale = { 0.055977, 0.212564, 0.475515 },
                },
                {
                    name = "glow (3)",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "MT_ThrusterGlow" },
                    position = { 0.1192, -0.0698, 0 },
                    rotation = { 0, 0, 240 },
                    scale = { 0.055977, 0.212564, 0.475515 },
                },
            },
        },
        {
            name = "warhead",
            position = { 0, 0, 0.25 },
            rotation = { 0, 0, 0 },
            scale = { 0.32205, 0.32205, 0.32205 },
            weapon = {
                weaponID = 1015036,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
        },
        {
            name = "trail",
            position = { 0, 0, -0.65 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            particleEmitter = {
                particleType = "RIBBON",
                distancePerParticle = 0,
                minSecondsPerParticle = 0,
                ejectionVelocity = 0,
                ejectionVelocityAwayFromEmitter = false,
                requiredVelocityAlignmentDegrees = 0,
                randomRadius = 0,
                randomScaleMinFraction = 0,
                startDisabled = false,
                stateToggleTrigger = "None",
                colourStart = { 1, 0, 0 },
                colourEnd = { 0, 0, 1 },
                opacity = 1,
                scaleStart = 0.5,
                scaleEnd = 0.5,
                lifetime = 3,
            },
        },
    },
    unitCore = true,
    physicsShape = {
        shapeType = "Capsule",
        center = { 0, 0, 0 },
        radius = 0.136613,
        height = 1,
        orientation = { 0, 0, 0 },
        collisionResponse = "Collide",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    ghostMesh = "01_missile_kontalagrad/01_missile_kontalagrad",
    ghostMaterials = { "01_MT_Ghost_TeamColour", "01_MT_BaseColour_ship_primary", "01_MT_Glow_dead" },
    ghostParts = {
        {
            name = "glow",
            mesh = "01_missile_kontalagrad/01_missile_kontalagrad",
            materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
        },
    },
    health = {
        unitClass = "MEDIUM",
        health = 700,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 2,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 10,
        heatResistancePercentage = 0.5,
        shredResistancePercentage = 0,
        aegisMaximum = 300,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = true,
        ignoreImpulse = true,
        specialType = 0,
        targetingPriorityMultiplier = 2,
        untargetableTime = 3,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 12,
        flashSizeOverride = 8,
        forceShockwave = true,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "FREE",
        maximumAngleToTarget = 6.28318,
        acceleration = 1.5,
        strafingAccelMultiplier = 0,
        reverseAccelMultiplier = 0,
        inertialCorrection = true,
        isStrafing = false,
        alwaysThrust = false,
        launchDumbThrustSeconds = 3,
        standoffDistance = 0,
        retreatDistance = 0,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = true,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 30,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = false,
    },
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "MACRO_ONLY",
            isFriendly = false,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = false,
            ignoreUncapturable = false,
            ignoreNonHealRequester = false,
            targetOnlySpecialType = 0,
            secondsPerScan = 0,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 80,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 1,
            scoreForHealth = 0.0001,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = 0,
            scoreForAngle = -0.05,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 0,
            perceivedDistanceMin = 10,
            classMultMissile = -1,
            classMultDrone = -1,
            classMultLight = -1,
            classMultMedium = -1,
            classMultHeavy = 0.1,
            classMultCapital = 1,
            classMultTitan = 1.2,
            shipMultiplier = 0,
            structureMultiplier = 1.1,
            keepTargetMultiplier = 5,
            scoreBandingSize = 0,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "MISSILE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = true,
    payload = {
        damage = {
            isNondamaging = false,
            instances = 50,
            damage = 250,
            piercing = 0,
            shred = 0,
            heat = 125,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        areaEffect = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 8,
            radiusInner = 3,
            waveSteps = 0,
            waveSeconds = 0,
        },
    },
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
