return {
    unitName = "bullet_gregor",
    unitDisplayName = "Point-Shadow Undulation",
    unitTooltip = "",
    unitBlurb = "Spatiotemporal force wave.",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_14013_bullet_gregor.png",
    controllable = false,
    unselectable = true,
    untargetable = true,
    unhittable = true,
    data = {
        typeID = 1014013,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "0",
        requiredLevelForDescription = "",
        tactical = "",
        description = "",
        weaponInfo = {
            { -1, -1, -1 },
            { 1015060, 1, 0 },
        },
    },
    scale = 0.6,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    parts = {
        {
            name = "warhead",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015060,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            scaleModifier = true,
        },
        {
            name = "model",
            mesh = "01_bullet_gregor/01_bullet_gregor",
            materials = { "01_material_plasma_gregor", "01_material_plasma_gregor_core" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.2, 1.2, 1.2 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 0, 150 },
            },
        },
        {
            name = "ParticleEmitter",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.666667, 1.666667, 1.666667 },
            particleEmitter = {
                particleType = "PARTICLE",
                distancePerParticle = 0.1,
                minSecondsPerParticle = 0,
                ejectionVelocity = 0,
                ejectionVelocityAwayFromEmitter = false,
                requiredVelocityAlignmentDegrees = 0,
                randomRadius = 0.05,
                randomScaleMinFraction = 0.8,
                startDisabled = false,
                stateToggleTrigger = "None",
                colourStart = { 0.4, 0.2, 1 },
                colourEnd = { 0.4, 0.05, 0.2 },
                opacity = 0.75,
                scaleStart = 0.4,
                scaleEnd = 0.15,
                lifetime = 0.65,
            },
        },
    },
    unitCore = true,
    health = {
        unitClass = "NONE",
        health = 1,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 0,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 21,
        explosionSFXIntensity = 2,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 9,
        lifetimeStd = 0,
        explodeOnTimeout = true,
        explosionType = "POINTSHADOW",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 3,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "FREE",
        maximumAngleToTarget = 10,
        acceleration = 1,
        strafingAccelMultiplier = 1,
        reverseAccelMultiplier = 1,
        inertialCorrection = true,
        isStrafing = false,
        alwaysThrust = false,
        launchDumbThrustSeconds = 0,
        standoffDistance = 0,
        retreatDistance = 0,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 28,
        maxSpeedMultiplier = 10,
        preferredAngle = 0,
        ignoreWorldUp = true,
    },
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_ONLY",
            isFriendly = false,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = true,
            ignoreUncapturable = false,
            ignoreNonHealRequester = false,
            targetOnlySpecialType = 0,
            secondsPerScan = 1,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 28,
            maximumAngle = 1.6,
            addedPreaimDistance = 0,
            scoreForDistance = 1,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = -0.1,
            scoreForArmourCurrent = 0,
            scoreForAngle = -0.03,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 25,
            perceivedDistanceMin = 0,
            classMultMissile = -1,
            classMultDrone = -1,
            classMultLight = 0.33,
            classMultMedium = 1,
            classMultHeavy = 0.66,
            classMultCapital = 0.5,
            classMultTitan = 0.33,
            shipMultiplier = 2,
            structureMultiplier = 0,
            keepTargetMultiplier = 2,
            scoreBandingSize = 5,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "MISSILE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 1.5,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = true,
    payload = {
        damage = {
            isNondamaging = false,
            instances = 3,
            damage = 105,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0.15,
        },
        areaEffect = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 2.5,
            radiusInner = 1.5,
            waveSteps = 0,
            waveSeconds = 0,
        },
    },
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
