return {
    unitName = "2x2_yard_drone",
    unitDisplayName = "Yard D4",
    unitTooltip = "",
    unitBlurb = "Drone Construction Yard",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "V",
    picture = "1_12031_2x2_yard_drone.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012031,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 30,
        cost_energy = 0,
        cost_supply = 4,
        cost_time = 15,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "- - -\n\nThe Mk17 dedicated drone yard. Able to produce the Jipper fighter and Hemnok bomber. Largely discontinued from service due to the efficacy of the Yard L1 and Light-kind vessels.\n\nInitially the Yard D4 was designed for perimiter defence and \"stocked up\" on drones. Releasing them in waves upon the approach of hostile forces intending to harass or otherwise flank bases with exposed sections. Effectively providing a large area defence net far cheaper than defencive turrets would provide.\n\nHowever the unfortunate reality of this rather edge-case scenario - a Kontaalen base left without light forces pouring out of it to handle such a perimiter intrusion - was self evident. Leaving the D4 shelved rather quickly after it's initial trial period.\n\nUntil a turncoat Vaalkorei commander complained of being unable to perform drone-strike operations using Kontaalen doctrine. This got the Fleet Development Core hot under the collar, and soon the D4 was returned to edge-case service and heavily reworked to provide constant drone production. Though it is still left out of standard service packages.\n\n\nDuring the D4's trial phase, it suffered a very odd issue that resulted in it's drones not properly decaying upon end-of-life. Causing the surrounding testing-facility to be hailed upon by hundreds of jipper husks, sadly resulting in the loss of the staff breakroom's glass flower vase, and an antenna.",
    },
    scale = 2,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_yard_drone/01_yard_drone",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "unitBubble(Clone)",
            mesh = "01_yard_drone/01_yard_drone",
            materials = { "01_MT_Aegis", "01_MT_Aegis", "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.0972, 1.0972, 1.0972 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0.145, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.86967, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "01_structure_prop_scafold_small",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0.25, -0.16673, 0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 0.574931, 0.5 },
                },
                {
                    name = "glow",
                    mesh = "01_yard_drone/01_yard_drone",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, -0.16673, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1.149861, 1 },
                },
                {
                    name = "01_structure_prop_scafold_small (1)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { -0.25, -0.16673, 0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 0.574931, 0.5 },
                },
                {
                    name = "01_structure_prop_scafold_small (2)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { -0.25, -0.16673, -0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 0.574931, 0.5 },
                },
                {
                    name = "01_structure_prop_scafold_small (3)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0.25, -0.16673, -0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 0.574931, 0.5 },
                },
            },
        },
        {
            name = "Spawnpoint",
            position = { -0.25, 0.096497, -0.25 },
            rotation = { 0, 0, 0 },
            scale = { 0.5, 0.5, 0.5 },
            spawnerSpawnPoint = {
                code = 0,
            },
        },
        {
            name = "Spawnpoint (1)",
            position = { 0.25, 0.096497, -0.25 },
            rotation = { 0, 0, 0 },
            scale = { 0.5, 0.5, 0.5 },
            spawnerSpawnPoint = {
                code = 0,
            },
        },
        {
            name = "Spawnpoint (2)",
            position = { 0.25, 0.096497, 0.25 },
            rotation = { 0, 0, 0 },
            scale = { 0.5, 0.5, 0.5 },
            spawnerSpawnPoint = {
                code = 0,
            },
        },
        {
            name = "Spawnpoint (3)",
            position = { -0.25, 0.096497, 0.25 },
            rotation = { 0, 0, 0 },
            scale = { 0.5, 0.5, 0.5 },
            spawnerSpawnPoint = {
                code = 0,
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, -0.05, 0 },
        size = { 0.95, 0.3, 0.95 },
        orientation = { 0, 0, 0 },
        bevelRadius = 1,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "HEAVY",
        health = 1500,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 5,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 2.5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "PRODUCTION",
        ring = { 0, 0 },
        rectangle = { 2, 2 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = true,
    spawner = {
        spawnOffset = { 0, 2.5, 0 },
        spawnOffsetHeightRandomisation = 1,
        endRotationUseStructureForward = false,
        noUnitGhost = false,
        usesToSelfdestruct = 0,
        simultaniousUnitLimit = 0,
        arrivalData = {
            type = "ARRIVE",
            arrivalDuration = 2,
            approachSpeed = 0.75,
            keepDisabled = false,
        },
    },
    spawnerCapacity = {
        current = 0,
    },
    spawnItems = {
        {
            id = 1011008,
            spawnTime = 15,
            spawnTimeStart = 15,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011016,
            spawnTime = 45,
            spawnTimeStart = 45,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
    },
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 2,
    },
}
