return {
    unitName = "5x4_gantry_untres",
    unitDisplayName = "Forge Gantry",
    unitTooltip = "",
    unitBlurb = "Forge-Powered Capital Vessel Constructor",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "H",
    picture = "1_12038_5x4_gantry_untres.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012038,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 500,
        cost_energy = 500,
        cost_supply = 0,
        cost_time = 60,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "DISCOVER",
        requiredLevelForVisible = "12013",
        requiredLevelForDescription = "",
        tactical = "- Heart powered production facility.",
        description = "- - -\n\n[Exerpt from Forge Heart analysis by J. Egressa]\n...we took what we could from Apocrypha and mixed it with our other aquirements from across the Spance...",
    },
    scale = 9,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_gantry_forge/01_gantry_forge",
    materials = { "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "Vortex A",
            mesh = "vortex/vortex_fill",
            materials = { "mt_vortex_heart" },
            position = { 0, 0.285, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.875965, -0.188206, 0.875965 },
            vortex = true,
        },
        {
            name = "Vortex A (1)",
            mesh = "vortex/vortex_fill",
            materials = { "mt_vortex_heart" },
            position = { 0, -0.285, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.875965, 0.188206, 0.875965 },
            vortex = true,
        },
        {
            name = "Vortex huge",
            mesh = "vortex/vortex_cohesionarray",
            materials = { "mt_vortex_coheser_rect2" },
            position = { 0, -0.074, 0 },
            rotation = { 0, 0, 180 },
            scale = { 5.018981, 1.25, 5.018981 },
            vortex = true,
        },
        {
            name = "Vortex huge top",
            mesh = "vortex/vortex_cohesionarray",
            materials = { "mt_vortex_coheser_rect2" },
            position = { 0, 0.074, 0 },
            rotation = { 0, 0, 0 },
            scale = { 5.018981, 1.25, 5.018981 },
            vortex = true,
        },
        {
            name = "launchpoint",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            spawnerSpawnPoint = {
                code = 0,
            },
        },
        {
            name = "01_gantry_forge_ring",
            mesh = "01_gantry_forge/01_gantry_forge_ring",
            materials = { "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_structure_primary", "01_MT_ShadowGlow" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, -5, 0 },
            },
        },
        {
            name = "01_gantry_forge_ring (1)",
            mesh = "01_gantry_forge/01_gantry_forge_ring",
            materials = { "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_structure_primary", "01_MT_ShadowGlow" },
            position = { 0, 0.163, 0 },
            rotation = { 0, 245.1074, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 10, 0 },
            },
        },
        {
            name = "01_gantry_forge_ring (2)",
            mesh = "01_gantry_forge/01_gantry_forge_ring",
            materials = { "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_structure_primary", "01_MT_ShadowGlow" },
            position = { 0, -0.163, 0 },
            rotation = { 0, 74.69925, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 8, 0 },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Cylinder",
        center = { 0, 0, 0 },
        radius = 0.5,
        height = 0.422184,
        orientation = { 90, 0, 0 },
        bevelRadius = 1,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "CAPITAL",
        health = 20000,
        health_regen_per_second = 20,
        max_regen_frac = 0,
        armour = 10,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "PRODUCTION",
        ring = { 0, 0 },
        rectangle = { 9, 9 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = true,
    spawner = {
        spawnOffset = { 0, 5, 0 },
        spawnOffsetHeightRandomisation = 1,
        endRotationUseStructureForward = false,
        noUnitGhost = false,
        usesToSelfdestruct = 0,
        simultaniousUnitLimit = 0,
        arrivalData = {
            type = "ARRIVE",
            arrivalDuration = 5,
            approachSpeed = 2,
            keepDisabled = false,
        },
    },
    spawnerCapacity = {
        current = 0,
    },
    spawnItems = {
        {
            id = 1011004,
            spawnTime = 50,
            spawnTimeStart = 50,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011020,
            spawnTime = 30,
            spawnTimeStart = 30,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011010,
            spawnTime = 40,
            spawnTimeStart = 40,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011027,
            spawnTime = 50,
            spawnTimeStart = 50,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011015,
            spawnTime = 60,
            spawnTimeStart = 60,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
    },
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
