return {
    unitName = "partell_torpedo",
    unitDisplayName = "Wick Torpedo",
    unitTooltip = "",
    unitBlurb = "Long Range Torpedo, Significant Photon Explosive",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_14003_partell_torpedo.png",
    controllable = false,
    unselectable = true,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1014003,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "0",
        requiredLevelForDescription = "",
        tactical = "",
        description = "",
        weaponInfo = {
            { 1015023, 1, 0 },
        },
    },
    scale = 0.17,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_torpedo_partell/01_torpedo_partell",
    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "thruster_glow",
            position = { 0, 0, -0.435 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_ultralowPoly/thrusterplume_utralowpolly",
                    materials = { "01_MT_ThrusterGlow_opaque_bright" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 0.5, 1 },
                },
            },
        },
        {
            name = "warhead",
            position = { 0, 0, 0.11 },
            rotation = { 0, 0, 0 },
            scale = { 0.32205, 0.32205, 0.32205 },
            weapon = {
                weaponID = 1015023,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            scaleModifier = true,
        },
        {
            name = "ParticleEmitter",
            position = { 0, 0, -0.426 },
            rotation = { 0, 0, 0 },
            scale = { 0.647059, 0.647059, 0.647059 },
            particleEmitter = {
                particleType = "RIBBON",
                distancePerParticle = 0,
                minSecondsPerParticle = 0,
                ejectionVelocity = -1,
                ejectionVelocityAwayFromEmitter = false,
                requiredVelocityAlignmentDegrees = 0,
                randomRadius = 0,
                randomScaleMinFraction = 0,
                startDisabled = false,
                stateToggleTrigger = "None",
                colourStart = { 0.75, 1.125, 1.5 },
                colourEnd = { 0.5, 0.5, 0.5 },
                opacity = 0.4,
                scaleStart = 0.04,
                scaleEnd = 0,
                lifetime = 0.15,
            },
        },
    },
    unitCore = true,
    physicsShape = {
        shapeType = "Capsule",
        center = { 0, 0, 0 },
        radius = 0.3,
        height = 1,
        orientation = { 0, 0, 0 },
        collisionResponse = "Collide",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "MISSILE",
        health = 12,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 0,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0.4,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = true,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0.15,
        phaseBlockFraction = 0,
        lifetime = 4.2,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0.65,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
