return {
    unitName = "OwO_bullet_heavyrail",
    unitDisplayName = "",
    unitTooltip = "",
    unitBlurb = "",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "3_34004_0x0_bullet_heavyrail.png",
    controllable = false,
    unselectable = true,
    untargetable = true,
    unhittable = true,
    data = {
        typeID = 6664001,
        factionID = 666,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "",
        weaponInfo = {
            { 6666001, 1, 0 },
        },
    },
    scale = 0.45,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "bullet_heavyrail/bullet_heavyrail",
    materials = { "03_material_railtracer" },
    parts = {
        {
            name = "warhead",
            position = { 0, 0, 1.33 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 6666001,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            scaleModifier = true,
        },
        {
            name = "ParticleEmitter",
            position = { 0, 0, 0.8067 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            particleEmitter = {
                particleType = "RIBBON",
                distancePerParticle = 0,
                minSecondsPerParticle = 0,
                ejectionVelocity = 0,
                ejectionVelocityAwayFromEmitter = false,
                requiredVelocityAlignmentDegrees = 0,
                randomRadius = 0,
                randomScaleMinFraction = 0,
                startDisabled = false,
                stateToggleTrigger = "None",
                colourStart = { 0.9, 1.2, 2 },
                colourEnd = { 0.6, 0.8, 1 },
                opacity = 1,
                scaleStart = 0.035,
                scaleEnd = 0.01,
                lifetime = 1,
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.5,
        angularDamping = 0.5,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    health = {
        unitClass = "NONE",
        health = 1,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 0,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 4,
        explosionSFXIntensity = 1,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 2,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "SPARKS",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 6,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
