return {
    unitName = "missile_AProcket",
    unitDisplayName = "",
    unitTooltip = "",
    unitBlurb = "",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "6_64004_missile_AProcket.png",
    controllable = false,
    unselectable = true,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 6664008,
        factionID = 666,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "0",
        requiredLevelForDescription = "",
        tactical = "",
        description = "",
        weaponInfo = {
            { 6666008, 1, 0 },
        },
    },
    scale = 0.4,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "666_AProcket/06_AProcket",
    materials = { "666_material_teamGlow", "666_material_teamColour_pirate", "666_material_dark_1", "666_material_chrome" },
    parts = {
        {
            name = "thruster_glow",
            position = { 0, 0, -0.1918 },
            rotation = { 0, 0, 0 },
            scale = { 0.1, 0.1, 0.1 },
            thruster = {
                decayTime = 1,
                workWhenThrustWithinAngleDegrees = 63,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume/thruster_plume",
                    materials = { "MT_ThrusterGlow" },
                    position = { 0, 0, -0.032 },
                    rotation = { 0, 0, 0 },
                    scale = { 1.204625, 1.204625, 1.936905 },
                },
            },
        },
        {
            name = "warhead",
            position = { 0, 0, 0.136 },
            rotation = { 0, 0, 0 },
            scale = { 0.32205, 0.32205, 0.32205 },
            weapon = {
                weaponID = 6666008,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            scaleModifier = true,
        },
        {
            name = "ParticleEmitter",
            position = { 0, 0, -0.108 },
            rotation = { 0, 0, 0 },
            scale = { 3.02885, 3.02885, 3.02885 },
            particleEmitter = {
                particleType = "PARTICLE",
                distancePerParticle = 0.05,
                minSecondsPerParticle = 0,
                ejectionVelocity = -0.9,
                ejectionVelocityAwayFromEmitter = false,
                requiredVelocityAlignmentDegrees = 0,
                randomRadius = 0,
                randomScaleMinFraction = 0,
                startDisabled = false,
                stateToggleTrigger = "None",
                colourStart = { 1, 0.9, 0.8 },
                colourEnd = { 0.5, 0.5, 0.5 },
                opacity = 0.4,
                scaleStart = 0.1,
                scaleEnd = 0.2,
                lifetime = 0.9,
            },
        },
    },
    unitCore = true,
    health = {
        unitClass = "MISSILE",
        health = 22,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 1,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = true,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        doesCloaking = false,
        isCloaked = false,
        cloakFrac = 0,
        cloakTime = 0,
        decloakDistance = 0,
        phaseBlockFraction = 0,
        lifetime = 3.5,
        lifetimeStd = 0,
        explodeOnTimeout = true,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "FREE",
        maximumAngleToTarget = 6.28318,
        acceleration = 3.5,
        strafingAccelMultiplier = 0,
        reverseAccelMultiplier = 0,
        inertialCorrection = false,
        isStrafing = false,
        alwaysThrust = false,
        launchDumbThrustSeconds = 0,
        missileFinForceFraction = 0,
        finForceToFacing = false,
        standoffDistance = 0,
        retreatDistance = 0,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 0,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = false,
    },
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_AND_MACRO",
            isFriendly = false,
            isResourceMiner = false,
            acceptFirstValidTarget = true,
            pauseIfHasTarget = true,
            ignoreUncapturable = false,
            ignoreNonHealRequester = false,
            targetOnlySpecialType = 0,
            secondsPerScan = 0,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 15,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 0,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = 0,
            scoreForAngle = 0,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 0,
            perceivedDistanceMin = 0,
            classMultMissile = 0,
            classMultDrone = 0,
            classMultLight = 0,
            classMultMedium = 0,
            classMultHeavy = 0,
            classMultCapital = 0,
            classMultTitan = 0,
            shipMultiplier = 0,
            structureMultiplier = 0,
            keepTargetMultiplier = 0,
            scoreBandingSize = 0,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "NONE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
