return {
    unitName = "turret_defence",
    unitDisplayName = "Watcher Spire",
    unitTooltip = "",
    unitBlurb = "Missile & Drone Defence",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "F",
    picture = "1_12028_turret_defence.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012028,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 6,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 5,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Anti-Missile Turret</color>\nDesigned to hold off missiles and early drone aggression.\n- Strong against Missiles.\n- Decent against Drones.\n- Poor against Ships.",
        description = "- - -\nInfo:\n\nAn unassuming and simple miniaturisation of the famous Beam Spire. The Watcher performs much the same task at far smaller scales, while packing a diffractive area of effect attack that is truly devestating against drone swarms.\n\nThe Watcher has been through many many iterations during it's serving time in the Armada roster. Originally, it was a gimbled tolly gun with the minor issue of ripping itself off it's mounting and flying off into the Spance. Eventually, someone just gave up and said \"Beam Spire but tiny\". The rest is history.\n\nMr Halliel of the Porters Planetary Guild, once attempted to have the Watchers around his settlement retrofitted into disco-lights for a year-end function. Saying \"It's only point light, what's the harm?\". The resulting damage to property across the settlement cost the Guild over 20,000,000 crowns.",
        weaponInfo = {
            { 1015059, 1, 0 },
        },
    },
    scale = 0.8,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    displayAreaRadius = 7,
    displayAreaColour = { 1, 0, 0, 0.25098 },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_turret_pd/01_structure_pd",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_PointLightGlow_Low", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_structure_secondary" },
    parts = {
        {
            name = "turret_beam",
            position = { 0, 0.549, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015059,
                turnSpeed = 229.1831,
                turnMode = "Linear",
                turnInstant = true,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 45,
                    down = 25,
                },
            },
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 1, 0.534641, 0.2, 1 },
                        intensity = 1.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_aegis_icosphere/01_aegis_icosphere",
            materials = { "01_MT_Aegis" },
            position = { 0, 0.218, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.827761, 0.827761, 0.827761 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_small",
            position = { 0, 0.256, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.856922, 0.856922, 0.856922 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0.079, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_turret_pd/01_structure_pd",
                    materials = { "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1" },
                    position = { 0, -0.298744, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1.166967, 1.166967, 1.166967 },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Sphere",
        center = { 0, 0, 0 },
        radius = 0.42,
        orientation = { 0, 0, 0 },
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "LIGHT",
        health = 300,
        health_regen_per_second = 3,
        max_regen_frac = 0,
        armour = 5,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0.5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 1.2,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013020,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "DEFENCE",
        ring = { 0, 0 },
        rectangle = { 1, 1 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 1,
    },
}
