return {
    unitName = "Vein Portal",
    unitDisplayName = "Vein Portal",
    unitTooltip = "Kontaalen Warp-Stream Projection Super Structure",
    unitBlurb = "Warp-Stream Projector",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_12013_Vein Portal.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012013,
        factionID = 101,
        macroType = "TRUE",
        cost_matter = 100000,
        cost_energy = 100000,
        cost_supply = 10000,
        cost_time = 3000,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "HIDDEN",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "Interstellar Gravitationally Stabilised Warp Conduit.",
    },
    scale = 30,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_hero_VeinPortal/01_hero_VeinPortal",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_teamColour" },
    parts = {
        {
            name = "unitBubble",
            mesh = "01_hero_VeinPortal/01_hero_VeinPortal",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.0501, 1.0501, 1.0501 },
            aegisVisual = true,
        },
        {
            name = "Cylinder",
            mesh = "01_effect_veinCylinder_funnel/01_effect_veinCylinder_funnel",
            materials = { "mt_vortex_veinway_core" },
            position = { 0, 0.0025, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.334833, 0.334833, 0.334833 },
            vortex = true,
        },
        {
            name = "Vortex A (1)",
            mesh = "vortex/vortex_fill",
            materials = { "mt_vortex_veinway_mouth_outer" },
            position = { 0, 0.0425, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.172712, 0.233708, 1.172712 },
            vortex = true,
        },
        {
            name = "Ring",
            mesh = "01_hero_VeinPortal/01_hero_VeinPortal_ring",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 1.485083, 0 },
            },
        },
        {
            name = "Ring (1)",
            mesh = "01_hero_VeinPortal/01_hero_VeinPortal_ring",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
            position = { 0, -0.1, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 1.886569, 0 },
            },
        },
        {
            name = "Ring (2)",
            mesh = "01_hero_VeinPortal/01_hero_VeinPortal_ring",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
            position = { 0, -0.2, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 2.404633, 0 },
            },
        },
        {
            name = "Ring (3)",
            mesh = "01_hero_VeinPortal/01_hero_VeinPortal_ring",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
            position = { 0, -0.3, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 2.634668, 0 },
            },
        },
        {
            name = "Ring (4)",
            mesh = "01_hero_VeinPortal/01_hero_VeinPortal_ring",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
            position = { 0, -0.4, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 1.18331, 0 },
            },
        },
        {
            name = "Ring (5)",
            mesh = "01_hero_VeinPortal/01_hero_VeinPortal_ring",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
            position = { 0, -0.5, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 2.32605, 0 },
            },
        },
    },
    physicsShape = {
        shapeType = "Cylinder",
        center = { 0, 0, 0 },
        radius = 0.34,
        height = 0.1,
        orientation = { 270, 270, 0 },
        bevelRadius = 2,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "TITAN",
        health = 500000,
        health_regen_per_second = 150,
        max_regen_frac = 0,
        armour = 10,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = true,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "PRODUCTION",
        ring = { 0, 0 },
        rectangle = { 30, 30 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
