return {
    unitName = "drone_mechanic",
    unitDisplayName = "Mechanic",
    unitTooltip = "Freaking cruise missile in a trenchcoat",
    unitBlurb = "Repair drone",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "M",
    picture = "tempPng",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 666109,
        factionID = 666,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 19003,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Hull Repair</color>\nDesigned to repair Heavies and Capitals.\n- Repairs Health / Armour of allies.\n- Strong at supporting Heavies / Capitals.\n- <color=orange>Cannot Be Repaired</color>\n- Unarmed.",
        description = "- A little derpy, but we love her.\n\n- - -\nMATESSA\nLove For Family (transliteration, direct translation not possible)\n\nAn uncommon support vessel, employed to support Heavy and Capital dependent forces as well as support frontline outposts.\n\nThe Matessa, has a troubled design history rivaled only by the Kana. It's hull design has gone through numerous iterations, seeking for an optimal design to facilitate it's repair systems.\n\nIt's repair projector is able to knit wiring and shattered plates. Rapidly restoring vessels to operational standards. However, there is only so much it can do.\n\n\nFleetmarshal Prosallia once commented that the Matessa was only as effective as the forces protecting it. Citing her own experiences fighting off rogue pirate fleets during \"The Dust Run\" in which she utilised Abrundonells, Matessas, and Hakurrs to great effect.",
        weaponInfo = {
            { 6665014, 1, 0 },
        },
    },
    scale = 0.3,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 0.5,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "666_ship_drone_mechanic/666_ship_drone_mechanic",
    materials = { "666_material_base_pirate", "666_material_teamColour_pirate", "666_material_teamGlow"},
    parts = {        
        {
            name = "thruster_glow",
            position = { 0, 0, -0.061634 },
            rotation = { 0, 0, 0 },
            scale = { 0.3, 0.3, 0.6 },
            thruster = {
                decayTime = 1,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "MT_ThrusterGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
        {
            name = "turret_repair",
            position = { 0, 0, 0.566847 },
            rotation = { 0, 0, 0 },
            scale = { 0.4, 0.4, 0.4 },
            weapon = {
                weaponID = 6665014,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 9,
                    right = 9,
                    up = 9,
                    down = 9,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.1, 0.1, 0.1 },
                    weaponVisualConfig = {
                        laserColour = { 0.554529, 1, 0.447059, 1 },
                        intensity = 3.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },    
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.5,
        angularDamping = 0.5,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, -0.05 },
        size = { 0.680669, 0.201687, 0.576478 },
        orientation = { 0, 0, 0 },
        bevelRadius = 0.081407,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "DRONE",
        health = 40,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 2,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 1,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = true,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0.9,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 60,
        lifetimeStd = 0,
        explodeOnTimeout = true,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 6664011,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0.5,
        mass = 0,
        densityMult = 1,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "MAPLOCKED",
        maximumAngleToTarget = 0.5,
        acceleration = 0.35,
        strafingAccelMultiplier = 1,
        reverseAccelMultiplier = 0.5,
        inertialCorrection = true,
        isStrafing = true,
        alwaysThrust = false,
        launchDumbThrustSeconds = 0,
        standoffDistance = 3.5,
        retreatDistance = 3,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 1,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 20,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = false,
    },
    doAvoidance = false,
    avoidance = {
        considerationRadius = 8,
        considerStructures = false,
        considerMacroTargetStructures = false,
        drone = 0,
        missile = 0,
        light = 5,
        medium = 10,
        heavy = 10,
        capital = 10,
        titan = 10,
        avoidOnlyClosest = false,
        minimumThreatValue = 10,
        minimumThreatCount = 0,
        panicDistance = 0,
        unpanicDistance = 0,
    },
    isRepulsor = true,
    isNotRepulsed = false,
    repulsion = {
        interactionLayer = 0,
        weightOveride = 0,
        colliderDimensionsOverride = { 0, 0, 0 },
    },
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_AND_MACRO",
            isFriendly = true,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = false,
            ignoreUncapturable = false,
            ignoreNonHealRequester = true,
            targetOnlySpecialType = 0,
            secondsPerScan = 0.5,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 20,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 0.02,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0.02,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = 0,
            scoreForAngle = 0,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 0,
            perceivedDistanceMin = 0,
            classMultMissile = -1,
            classMultDrone = -1,
            classMultLight = -1,
            classMultMedium = 0.1,
            classMultHeavy = 2, 
            classMultCapital = 3,
            classMultTitan = 3,
            shipMultiplier = 5,
            structureMultiplier = 1,
            keepTargetMultiplier = 0,
            scoreBandingSize = 0,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "NONE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
