return {
    unitName = "aegis_emitter",
    unitDisplayName = "Aegis Emitter",
    unitTooltip = "",
    unitBlurb = "Base Shield Emitter",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "M",
    picture = "1_12019_aegis_emitter.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012019,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 75,
        cost_energy = 150,
        cost_supply = 0,
        cost_time = 30,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Shield Emitter</color>\nDesigned to give temporary bonus health to structures and ships.\n- Applies shielding to allied units.\n- Strong at supporting Drones / Lights.\n- Decent at supporting Mediums / Heavies / Capitals.\n- Detects cloaked units in aegis range.",
        description = "- - -\nInfo:\n\nAn exotic defence structure, used by advanced Kontaalen bases with sufficient energy, and those with a light / medium centric combat doctrine.\n\nThe Aegis Emitter was born from the development of the Solgasonder, when it was clear that the Aegis Core could prove usefull on it's own. Though the core had to be streamlined and downsized to fit within a standard operating base, the Emitter still maintains significant projection strength.",
        weaponInfo = {
            { 1015081, 1, 0 },
            { 1015084, 1, 0 },
        },
    },
    scale = 2,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    displayAreaRadius = 7,
    displayAreaColour = { 1, 0.685542, 0.55, 0.25098 },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_defence_aegisEmitter/01_defence_aegisEmitter",
    materials = { "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_structure_primary" },
    parts = {
        {
            name = "aegis_dummy",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015081,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
        },
        {
            name = "detector",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015084,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = true,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 180,
                    down = 180,
                },
            },
            scaleModifier = true,
        },
        {
            name = "Spinner",
            mesh = "01_defence_aegisEmitter/01_defence_aegisEmitter_ring",
            materials = { "01_MT_BaseColour_structure_primary" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 30, 0 },
            },
            piston = {
                localDistanceUp = 0.15,
                direction = "UpAndDown",
                startProgressFraction = 0,
                duration = 1,
            },
        },
        {
            name = "Spinner (1)",
            mesh = "01_defence_aegisEmitter/01_defence_aegisEmitter_ring",
            materials = { "01_MT_BaseColour_structure_secondary" },
            position = { 0, 0, 0 },
            rotation = { 0, 45.00003, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 30, 0 },
            },
            piston = {
                localDistanceUp = 0.15,
                direction = "UpAndDown",
                startProgressFraction = 0.5,
                duration = 1,
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_defence_aegisEmitter/01_defence_aegisEmitter_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_defence_aegisEmitter/01_defence_aegisEmitter",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
        {
            name = "ParticleEmitter",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            particleEmitter = {
                particleType = "PULSE",
                distancePerParticle = 4,
                minSecondsPerParticle = 0,
                ejectionVelocity = 0,
                ejectionVelocityAwayFromEmitter = false,
                requiredVelocityAlignmentDegrees = 0,
                randomRadius = 0,
                randomScaleMinFraction = 0,
                startDisabled = false,
                stateToggleTrigger = "OnDeath",
                colourStart = { 1, 0.37, 0.1 },
                colourEnd = { 1, 0.6, 0.45 },
                opacity = 0.2,
                scaleStart = 1,
                scaleEnd = 7,
                lifetime = 5,
            },
        },
    },
    unitCore = true,
    sphereCollider = {
        center = { 0, 0, 0 },
        radius = 0.5,
        isTrigger = false,
    },
    health = {
        unitClass = "HEAVY",
        health = 4000,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 20,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 2.5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 1.2,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "DEFENCE",
        ring = { 0, 0 },
        rectangle = { 2, 2 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = true,
    isAegisEmitter = true,
    aegisEmitter = {
        secondsPerPulse = 4,
        radius = 7,
        strength = 160,
    },
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 3,
    },
}
