return {
    unitName = "generator_matter_2x2",
    unitDisplayName = "Coheser",
    unitTooltip = "",
    unitBlurb = "Basic <color=green>Matter</color> Generator.",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "C",
    picture = "1_12003_generator_matter_2x2.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012003,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 50,
        cost_energy = 0,
        cost_supply = 1,
        cost_time = 7,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "<color=yellow>Tactical:</color>\n- Tough and compact matter coheser, made somewhat inefficient for price.\n\n- - -\nInfo:\n\nKontaal's heavily refined and optimised COH4 combat matter coheser.\n\nThe COH4 matter Coheser is at it's 53rd mark in it's long history in the Spance. The general design, a dynamic sift-mesh with magnetic oscilated threshing, can quickly gather and sort the bulk of <color=green>Matter</color> from the Spance's ambient dust. Allowing the rapid gathering of materials for construction of any facilities required on any battlefield.\n\nThe Vaalkorei have effectively reverse engineered Cohesion technology from the COH4 but have settled on a different doctrine of use. Where the Kontaalen focus on structural durability and compact design, the Coallition have managed to make more efficient output at the cost of a huge vulnerable structure profile.\n\nThere are many types of Coheser, some are the size of cities. The main limitation of course stopping this is sorting, storage, maintenance, production, and logistics capabilities. The larger a coheser, the more a nightmare the engineering and logistics become to facilitate it - however the tradeoffs change as scale does.",
    },
    scale = 2,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "structure_coheser/01_Structure_Coheser",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamColour" },
    parts = {
        {
            name = "Vortex A",
            mesh = "vortex/vortex_fill",
            materials = { "mt_vortex_coheser" },
            position = { 0, 0.159, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.930951, 0.309138, 0.930951 },
            vortex = true,
        },
        {
            name = "Vortex A (1)",
            mesh = "vortex/vortex_fill",
            materials = { "mt_vortex_coheser" },
            position = { 0, -0.159, 0 },
            rotation = { 0, 0, 180 },
            scale = { 0.930951, 0.309138, 0.930951 },
            vortex = true,
        },
        {
            name = "ring",
            mesh = "structure_coheser/01_Structure_Coheser_ring",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 5, 0 },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "structure_coheser_aegis/01_Structure_Coheser_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.4, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "structure_coheser/01_Structure_Coheser",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 2.5, 1 },
                },
                {
                    name = "glow (1)",
                    mesh = "structure_coheser/01_Structure_Coheser_ring",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 2.5, 1 },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 0.9, 0.3, 0.9 },
        orientation = { 0, 0, 0 },
        bevelRadius = 1,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "MEDIUM",
        health = 2000,
        health_regen_per_second = 3,
        max_regen_frac = 0,
        armour = 5,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 2,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "ECONOMY",
        ring = { 0, 0 },
        rectangle = { 2, 2 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = true,
    resourceGeneration = {
        matter = 0.5,
        energy = 0,
        phase = 0,
    },
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 1,
    },
}
