return {
    unitName = "medium_matessa",
    unitDisplayName = "Matessa",
    unitTooltip = "",
    unitBlurb = "Medium Fleet Repair",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "M",
    picture = "1_11013_medium_matessa.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1011013,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 19003,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Hull Repair</color>\nDesigned to repair Heavies and Capitals.\n- Repairs Health / Armour of allies.\n- Strong at supporting Heavies / Capitals.\n- <color=orange>Cannot Be Repaired</color>\n- Unarmed.",
        description = "- A little derpy, but we love her.\n\n- - -\nMATESSA\nLove For Family (transliteration, direct translation not possible)\n\nAn uncommon support vessel, employed to support Heavy and Capital dependent forces as well as support frontline outposts.\n\nThe Matessa, has a troubled design history rivaled only by the Kana. It's hull design has gone through numerous iterations, seeking for an optimal design to facilitate it's repair systems.\n\nIt's repair projector is able to knit wiring and shattered plates. Rapidly restoring vessels to operational standards. However, there is only so much it can do.\n\n\nFleetmarshal Prosallia once commented that the Matessa was only as effective as the forces protecting it. Citing her own experiences fighting off rogue pirate fleets during \"The Dust Run\" in which she utilised Abrundonells, Matessas, and Hakurrs to great effect.",
        weaponInfo = {
            { 1015024, 1, 0 },
        },
    },
    scale = 1,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 0.5,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_ship_medium_matessa/01_ship_medium_matessa",
    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_ship_secondary" },
    parts = {
        {
            name = "glow",
            mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
            materials = { "01_MT_ThrusterGlow" },
            position = { -0.2977, 0, 0.0774 },
            rotation = { 0, 135, 0 },
            scale = { 0.164152, 0.117108, 0.246228 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
        },
        {
            name = "glow (1)",
            mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
            materials = { "01_MT_ThrusterGlow" },
            position = { -0.2727, 0, -0.169 },
            rotation = { 0, 45.00002, 0 },
            scale = { 0.164152, 0.117108, 0.246228 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
        },
        {
            name = "glow (2)",
            mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
            materials = { "01_MT_ThrusterGlow" },
            position = { -0.3485, 0, -0.0339 },
            rotation = { 0, 89.99997, 0 },
            scale = { 0.164152, 0.117108, 0.246228 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
        },
        {
            name = "glow (3)",
            mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
            materials = { "01_MT_ThrusterGlow" },
            position = { 0.2977, 0, 0.0774 },
            rotation = { 0, 225, 0 },
            scale = { 0.164152, 0.117108, 0.246228 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
        },
        {
            name = "glow (4)",
            mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
            materials = { "01_MT_ThrusterGlow" },
            position = { 0.3485, 0, -0.0339 },
            rotation = { 0, 270, 0 },
            scale = { 0.164152, 0.117108, 0.246228 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
        },
        {
            name = "glow (5)",
            mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
            materials = { "01_MT_ThrusterGlow" },
            position = { 0.2727, 0, -0.169 },
            rotation = { 0, 315, 0 },
            scale = { 0.164152, 0.117108, 0.246228 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
        },
        {
            name = "thruster_glow",
            position = { 0, 0, -0.337 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1.5 },
            thruster = {
                decayTime = 1,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { -0.144, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.278468, 0.198662, 0.278468 },
                },
                {
                    name = "glow (1)",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0.144, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.278468, 0.198662, 0.278468 },
                },
            },
        },
        {
            name = "turret_repair",
            position = { 0, 0, 0.3324 },
            rotation = { 0, 0, 0 },
            scale = { 0.4, 0.4, 0.4 },
            weapon = {
                weaponID = 1015024,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 90,
                    right = 90,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.1, 0.1, 0.1 },
                    weaponVisualConfig = {
                        laserColour = { 0.554529, 1, 0.447059, 1 },
                        intensity = 3.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "01_turret_repair_model",
                    mesh = "01_light_repair/01_turret_repair",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_Glow_Heal" },
                    position = { 0, -0.000017, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 0.8, 0.8, 0.8 },
                },
            },
        },
        {
            name = "deathflash",
            position = { 0.259, 0.068, -0.096 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "SPARKLER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0.4,
                    lifetime = 0.32,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0.32,
                        opacity = 0,
                        diameter = 0.4,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 2,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "deathflash (1)",
            position = { -0.044, 0.122, -0.393 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "SPARKLER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0.18,
                    lifetime = 0.12,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0.12,
                        opacity = 0,
                        diameter = 0.18,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 2,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "deathflash (2)",
            position = { 0.128, 0.083, 0.351 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "SPARKLER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0.22,
                    lifetime = 0.24,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0.24,
                        opacity = 0,
                        diameter = 0.22,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 1,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "deathflash (3)",
            position = { -0.23, 0.082, 0.231 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "SPARKLER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0.14,
                    lifetime = 0.1,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0.1,
                        opacity = 0,
                        diameter = 0.14,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 0.8,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_ship_medium_matessa/01_ship_medium_matessa",
            materials = { "01_MT_Aegis", "01_MT_Aegis", "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.1, 1.1, 1.1 },
            aegisVisual = true,
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.5,
        angularDamping = 0.5,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, -0.05 },
        size = { 0.680669, 0.201687, 0.576478 },
        orientation = { 0, 0, 0 },
        bevelRadius = 0.081407,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    ghostMesh = "01_ship_medium_matessa/01_ship_medium_matessa",
    ghostMaterials = { "01_MT_BaseColour_ship_primary", "01_MT_Glow_dead", "01_MT_BaseColour_ship_secondary", "01_MT_Ghost_TeamColour" },
    ghostParts = {
        {
            name = "turret_repair",
            position = { 0, 0, 0.362 },
            rotation = { 90, 0, 0 },
            scale = { 0.4, 0.4, 0.4 },
            parts = {
                {
                    name = "01_turret_repair",
                    mesh = "01_light_repair/01_turret_repair",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_Glow_Heal" },
                    position = { 0, -0.000017, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 0.8, 0.8, 0.8 },
                },
                {
                    name = "01_turret_repair_body",
                    mesh = "01_light_repair/01_turret_repair_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, -0.000017, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 0.8, 0.8, 0.8 },
                },
            },
        },
        {
            name = "glow",
            mesh = "01_ship_medium_matessa/01_ship_medium_matessa",
            materials = { "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
        },
    },
    health = {
        unitClass = "MEDIUM",
        health = 400,
        health_regen_per_second = 2,
        max_regen_frac = 0,
        armour = 5,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 1,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = true,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0.9,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013021,
        invulnerable = false,
        unkillable = false,
        death_countdown = 2.5,
        mass = 0,
        densityMult = 1.3,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "MAPLOCKED",
        maximumAngleToTarget = 0.5,
        acceleration = 0.18,
        strafingAccelMultiplier = 1,
        reverseAccelMultiplier = 0.5,
        inertialCorrection = true,
        isStrafing = false,
        alwaysThrust = false,
        launchDumbThrustSeconds = 0,
        standoffDistance = 3.5,
        retreatDistance = 3,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 17,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = false,
    },
    doAvoidance = true,
    avoidance = {
        considerationRadius = 8,
        considerStructures = false,
        considerMacroTargetStructures = false,
        drone = 0,
        missile = 0,
        light = 5,
        medium = 10,
        heavy = 10,
        capital = 10,
        titan = 10,
        avoidOnlyClosest = false,
        minimumThreatValue = 10,
        minimumThreatCount = 0,
        panicDistance = 0,
        unpanicDistance = 0,
    },
    isRepulsor = true,
    isNotRepulsed = false,
    repulsion = {
        interactionLayer = 0,
        weightOveride = 0,
        colliderDimensionsOverride = { 0, 0, 0 },
    },
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_AND_MACRO",
            isFriendly = true,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = false,
            ignoreUncapturable = false,
            ignoreNonHealRequester = true,
            targetOnlySpecialType = 0,
            secondsPerScan = 0.5,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 20,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 0.02,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0.01,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = 0,
            scoreForAngle = 0,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 0,
            perceivedDistanceMin = 0,
            classMultMissile = -1,
            classMultDrone = -1,
            classMultLight = 0.01,
            classMultMedium = 0.1,
            classMultHeavy = 2,
            classMultCapital = 3,
            classMultTitan = 3,
            shipMultiplier = 5,
            structureMultiplier = 0.1,
            keepTargetMultiplier = 0,
            scoreBandingSize = 0,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "NONE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 3,
    },
}
