return {
    unitName = "generator_matter_5x5",
    unitDisplayName = "Cohesion Facility",
    unitTooltip = "",
    unitBlurb = "Advanced <color=green>Matter</color> Generator.",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "F",
    picture = "1_12027_generator_matter_5x5.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012027,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 200,
        cost_energy = 300,
        cost_supply = 10,
        cost_time = 30,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "- <color=red>Explodes violently when destroyed.</color>",
        description = "- - -\nInfo:\n\nThe COH5 Mk9 Cohesion Facility is the utter pinnacle of matter cohesion in the Spance, unrivalled in all aspects.\n\nThe Kontaalen having been the first to pioneer the Spance, and having the most focused drive on raw resource acquisition, have unsurprisingly developed the most dangerous, powerful, and utterly terrifying cohesion facility known to humanity.\n\nThe system relies on a central graviton relapser. A device utilising the inverse nature of the Graviton Engine to induce gravity. Vacuuming up large volumes of matter and dust into a burning fusion converter, that can not only sift and refine materials, but convert small amounts of certain undesirable elements into other elements.\n\nAs such, it is clear to say this facility require monstrous amounts of power and an unreasonably low standard of safety to employ.\n\nThough the Armada is well adjusted to it now, the COH5 has had rather infamous failures, resulting in minor nuclear detonations and the \"cohesing\" of local base facilities along with vessels. None the less, these issues have all been mostly ironed out.",
    },
    scale = 5,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "structure_coheser_5x5/01_Structure_CohesionFacility_5x5",
    materials = { "01_MT_BaseColour_teamColour", "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_structure_secondary" },
    parts = {
        {
            name = "Vortex A",
            mesh = "vortex/vortex_fill",
            materials = { "mt_vortex_coheser" },
            position = { 0, 0.0114, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.091614, 0.36685, 1.091614 },
            vortex = true,
        },
        {
            name = "Vortex A (1)",
            mesh = "vortex/vortex_fill",
            materials = { "mt_vortex_coheser" },
            position = { 0, 0.1457, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.335169, 0.112638, 0.335169 },
            vortex = true,
        },
        {
            name = "unitBubble(Clone)",
            mesh = "structure_coheser_aegis/01_Structure_Coheser_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.5, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0.25, 0, 0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 1, 0.5 },
                },
                {
                    name = "model (1)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { -0.25, 0, 0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 1, 0.5 },
                },
                {
                    name = "model (2)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0.25, 0, -0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 1, 0.5 },
                },
                {
                    name = "model (3)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { -0.25, 0, -0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 1, 0.5 },
                },
                {
                    name = "glow",
                    mesh = "structure_coheser_5x5/01_Structure_CohesionFacility_5x5",
                    materials = { "01_MT_buildglow_5", "01_MT_buildglow_5", "01_MT_buildglow_5", "01_MT_buildglow_5" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 2, 1 },
                },
            },
        },
        {
            name = "Core",
            mesh = "structure_coheser_5x5/01_Structure_CohesionFacility_5x5_core",
            materials = { "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_structure_primary" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 3.634367, 4.947056, 3.840036 },
            },
        },
        {
            name = "Spinner",
            mesh = "structure_coheser_5x5/01_Structure_cohesionFacility_5x5_spinner",
            materials = { "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow" },
            position = { 0, 0, 0 },
            rotation = { 90, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 0, 3 },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 1, 0.4, 1 },
        orientation = { 0, 0, 0 },
        bevelRadius = 1,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "CAPITAL",
        health = 8000,
        health_regen_per_second = 10,
        max_regen_frac = 0,
        armour = 10,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 3,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = true,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013023,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "ECONOMY",
        ring = { 0, 0 },
        rectangle = { 5, 5 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = true,
    resourceGeneration = {
        matter = 5,
        energy = 0,
        phase = 0,
    },
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 2,
    },
}
