return {
    unitName = "light_kana",
    unitDisplayName = "Kana",
    unitTooltip = "",
    unitBlurb = "Light Fleet Defence",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "K",
    picture = "1_11021_light_kana.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1011021,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 19001,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Point Defence Support</color>\nDesigned to protect other Lights.\n- Strong against Drones / Missiles.\n- Decent against Lights.\n- Poor against 3+ Armour.",
        description = "- - -\nKANA\nLight\n\nA point-defence support vessel, able to shoot down incomming ordinance and severly reduce the capabilities of hostile forces reliant on munitions.\n\nThe engineering behind the Kana's beam array is amusing. Never before had such a compact form of defraction array been engineered. It's kin on the Beam Spire and Wernos are large, technically complex, and require time costly callibration. However, the Kana forgoes all these needs; by simply not caring about being anything more than \"not terrible\". It suffers greatly in range, and energy output, but is easy to produce and sufficiently effective.\n\nAcross it's lifespan, the Kana has gone through many weaponry changes and hull redesigns. From missile-based fleet support, to more mid-ranged turreted point-light. However after the Cease Fire was signed, it was finalised into it's present role of short range point-defence.",
        weaponInfo = {
            { 1015056, 1, 0 },
        },
    },
    scale = 0.4,
    colliderDimensions = {
        widthMultiplier = 1.2,
        heightMultiplier = 0.5,
        lengthMultiplier = 1.2,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_ship_light_kana/01_light_kana",
    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
    parts = {
        {
            name = "thruster_glow",
            position = { 0, 0, -0.476 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1.45 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0, 0.06, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.36036, 0.21, 0.36036 },
                },
                {
                    name = "glow (1)",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0, -0.06, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.36036, 0.21, 0.36036 },
                },
            },
        },
        {
            name = "deathflash",
            position = { 0, 0, -0.34 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "SPARKLER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0.1,
                    lifetime = 0.5,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0.5,
                        opacity = 0,
                        diameter = 0.1,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 0.02,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_AND_MACRO",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 0,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "unitBubble",
            mesh = "01_ship_light_kana/01_light_kana",
            materials = { "01_MT_Aegis", "01_MT_Aegis", "01_MT_Aegis", "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.1, 1.1, 1.1 },
            aegisVisual = true,
        },
        {
            name = "pd_laser_omni",
            position = { 0, 0, 0.341 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015056,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = true,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 80,
                    right = 80,
                    up = 110,
                    down = 110,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 1, 0.534641, 0.2, 1 },
                        intensity = 1.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "None",
        mass = 10,
        linearDamping = 0.5,
        angularDamping = 0.5,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Cylinder",
        center = { 0, 0, 0 },
        radius = 0.54,
        height = 0.25,
        orientation = { 90, 0, 0 },
        bevelRadius = 1,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    ghostMesh = "01_ship_light_kana/01_light_kana",
    ghostMaterials = { "01_MT_BaseColour_ship_primary", "01_MT_Ghost_TeamColour", "01_MT_Glow_dead", "01_MT_BaseColour_ship_secondary" },
    ghostParts = {
        {
            name = "glow",
            mesh = "01_ship_light_kana/01_light_kana",
            materials = { "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
        },
    },
    health = {
        unitClass = "LIGHT",
        health = 120,
        health_regen_per_second = 1,
        max_regen_frac = 0,
        armour = 3,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0.4,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013020,
        invulnerable = false,
        unkillable = false,
        death_countdown = 1,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "MAPLOCKED",
        maximumAngleToTarget = 0.3,
        acceleration = 0.35,
        strafingAccelMultiplier = 0.25,
        reverseAccelMultiplier = 0.6,
        inertialCorrection = true,
        isStrafing = true,
        alwaysThrust = false,
        launchDumbThrustSeconds = 0,
        standoffDistance = 4,
        retreatDistance = 3.5,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 43,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = true,
    },
    doAvoidance = false,
    isRepulsor = true,
    isNotRepulsed = false,
    repulsion = {
        interactionLayer = 0,
        weightOveride = 0,
        colliderDimensionsOverride = { 0, 0, 0 },
    },
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_AND_MACRO",
            isFriendly = false,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = false,
            ignoreUncapturable = false,
            ignoreNonHealRequester = false,
            targetOnlySpecialType = 0,
            secondsPerScan = 0.25,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 15,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 1,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = 0,
            scoreForAngle = 0,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 0,
            perceivedDistanceMin = 0,
            classMultMissile = -1,
            classMultDrone = 0.01,
            classMultLight = 1,
            classMultMedium = 1,
            classMultHeavy = 1,
            classMultCapital = 1,
            classMultTitan = 1,
            shipMultiplier = 1.5,
            structureMultiplier = 0,
            keepTargetMultiplier = 0,
            scoreBandingSize = 0,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "NONE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 1,
    },
}
