return {
    unitName = "medium_Ignus",
    unitDisplayName = "Ignus",
    unitTooltip = "",
    unitBlurb = "Armoured Heat Assault Frigate",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "F",
    picture = "tempPng.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 6661002,
        factionID = 666,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Armoured Assault</color>\nDesigned to draw-fire and push the line.\n- Strong against Mediums.\n- Decent against Lights / Heavies.\n- Poor against 50+ Armour.\n- Vulnerable to Artillery.",
        description = "- - -\nOTORELL\nValiant\n\nA tough assault vessel, geared towards effective combat against tough opponents. However lacking in range.\n\nThe Otorell - like most Kontaalen vessels - is made of hard-carbon and keramite alloy, two materials that are somewhat less than standard among the core human navies. None the less, they stand out in the field of spancial warfare. What is more common than metal in the waving dusts? Carbon. Using a rather brutish approach to graphene genesis, hardcarbon is made enmass for many different use cases. Keramite alloy, makes use of the various radioactive and nobel elements in any given gust of spance to create reasonably light weight yet effective armouring with very effective Aegis attraction.\n\nAll in all, the Otorell is heavily hulled and notably armoured in truly space age materials, optimised for rapid production within the Spance's conditions.\n\nIt's Thumper cannon is often refered to as an \"upscalled Tolly gun\" an accurate assessment. Mounted on a two-axis rotary turret, the Auto Thumper is devestating to most targets at close range. Unfortunately, the nature of point-light precludes use at longer ranges. Forcing the rather powerful weapon, to fill a more defencive role.\n\nFleetmarshal Japalser once commented, that the Otorel was an inevitable consequence of someone asking \"Can we make a larger Tolly?\". Inheriting all the problems that question held... as well as all the strengths.",
        weaponInfo = {
            { 6665002, 1, 0 },
        },
    },
    scale = 1.48,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 0.5,
        lengthMultiplier = 1.48,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "666_ship_medium_ignis/66_ship_ignis",
    materials = { "666_material_base_pirate", "666_material_teamGlow", "666_material_teamColour_pirate", "666_material_dark_1"},
    parts = {
        {
            name = "spinal_artillery",
            position = { 0.000218, -0.001122, 0.621968 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 6665002,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = true,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "barrel",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "laser_beam",
                    mesh = "weaponthrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "MTD_ThrusterGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    weaponVisualConfig = {
                        laserColour = { 0.612, 0.039, 0, 1 },
                        intensity = 10,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = true,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "deathflash",
            position = { 0.259, 0.068, -0.096 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "EXPLODER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 5,
                        damage = 10,
                        piercing = 0,
                        shred = 0,
                        heat = 40,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = true,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 5,
                        radiusInner = 2,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 5,
                    lifetime = 0.32,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "FLAK",
                    laserDescription = {
                        duration = 0.32,
                        opacity = 0,
                        diameter = 0.4,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 2,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "thruster_glow",
            position = { 0, 0, -0.333952 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.6, 3 },
            thruster = {
                decayTime = 1,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.511748, 0.325954, 0.234833 },
                },
            },
        },
        {
            name = "thruster_glow 1",
            position = { 0, -0.14154, -0.193175 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.6, 3 },
            thruster = {
                decayTime = 1,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.511748, 0.325954, 0.234833 },
                },
            },
        },
        {
            name = "thruster_glow 1",
            position = { 0, 0.14154, -0.193175 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.6, 3 },
            thruster = {
                decayTime = 1,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.511748, 0.325954, 0.234833 },
                },
            },
        },
        {
            name = "thruster_glow reverse",
            position = { 0, 0, -0.024 },
            rotation = { 0, 179.9999, 0 },
            scale = { 0.6, 0.6, 1 },
            thruster = {
                decayTime = 1,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { -0.261191, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.267066, 0.197959, 0.197959 },
                },
                {
                    name = "glow (1)",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0.261191, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.267066, 0.197959, 0.197959 },
                },
            },
        },
        {
            name = "thruster_glow reverse (1)",
            position = { 0.305566, 0, -0.111055 },
            rotation = { 0, 269.9999, 0 },
            scale = { 0.6, 0.6, 1 },
            thruster = {
                decayTime = 1,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.330432, 0.197959, 0.128208 },
                },
            },
        },
        {
            name = "thruster_glow reverse (2)",
            position = { -0.305566, 0, -0.111055 },
            rotation = { 0, 90, 0 },
            scale = { 0.6, 0.6, 1 },
            thruster = {
                decayTime = 1,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.330432, 0.197959, 0.128208 },
                },
            },
        },
        {
            name = "deathflash (1)",
            position = { -0.044, 0.122, -0.286 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "EXPLODER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 5,
                        damage = 10,
                        piercing = 0,
                        shred = 0,
                        heat = 40,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = true,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 5,
                        radiusInner = 2,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 5,
                    lifetime = 0.12,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "FLAK",
                    laserDescription = {
                        duration = 0.12,
                        opacity = 0,
                        diameter = 0.18,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 2,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "deathflash (2)",
            position = { 0.099, 0.083, 0.342 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "EXPLODER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 5,
                        damage = 10,
                        piercing = 0,
                        shred = 0,
                        heat = 40,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = true,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 5,
                        radiusInner = 2,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 5,
                    lifetime = 0.24,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "FLAK",
                    laserDescription = {
                        duration = 0.24,
                        opacity = 0,
                        diameter = 0.22,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 1.7,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "deathflash (3)",
            position = { -0.268, 0.082, 0.012 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "EXPLODER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 5,
                        damage = 10,
                        piercing = 0,
                        shred = 0,
                        heat = 40,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = true,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 5,
                        radiusInner = 2,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 5,
                    lifetime = 0.1,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "FLAK",
                    laserDescription = {
                        duration = 0.1,
                        opacity = 0,
                        diameter = 0.14,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 1.8,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_ship_medium_otorel_aegis/01_ship_medium_otorel_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "Colliders",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            parts = {
                {
                    name = "Body",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    physicsShape = {
                        shapeType = "Box",
                        center = { 0, 0, 0 },
                        size = { 0.463325, 0.223841, 0.977342 },
                        orientation = { 0, 0, 0 },
                        bevelRadius = 0.111921,
                        collisionResponse = "None",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
                {
                    name = "Wings",
                    position = { 0, 0, -0.029 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    physicsShape = {
                        shapeType = "Box",
                        center = { 0, 0, 0 },
                        size = { 0.881981, 0.189402, 0.311112 },
                        orientation = { 0, 0, 0 },
                        bevelRadius = 0.059749,
                        collisionResponse = "None",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.5,
        angularDamping = 0.5,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    ghostMesh = "01_ship_medium_otorel/01_ship_medium_otorel",
    ghostMaterials = { "01_MT_BaseColour_structure_primary", "01_MT_Glow_dead", "01_MT_BaseColour_ship_secondary", "01_MT_Ghost_TeamColour" },
    ghostParts = {
        {
            name = "turret_maingun",
            position = { 0, 0, 0.328 },
            rotation = { 0, 0, 90 },
            scale = { 0.5, 0.5, 0.5 },
            parts = {
                {
                    name = "gun",
                    mesh = "01_turret_medium_laser_otorel/01_turret_otorel_gun",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_medium_laser_otorel/01_turret_otorel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
        {
            name = "turret_maingun glow",
            position = { 0, 0, 0.328 },
            rotation = { 0, 0, 90 },
            scale = { 0.5, 0.5, 0.5 },
            parts = {
                {
                    name = "gun",
                    mesh = "01_turret_medium_laser_otorel/01_turret_otorel_gun",
                    materials = { "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_medium_laser_otorel/01_turret_otorel_body",
                    materials = { "01_MT_buildglow_1" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
        {
            name = "glow",
            mesh = "01_ship_medium_otorel/01_ship_medium_otorel",
            materials = { "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
        },
    },
    health = {
        unitClass = "MEDIUM",
        health = 950,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 19,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0.66,
        shredMultiplier = 1.5,
        explosionSFX = 0,
        explosionSFXIntensity = 1,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 6,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = true,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 6,
            radiusInner = 4,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 10,
            damage = 25,
            piercing = 0,
            shred = 0,
            heat = 50,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013021,
        invulnerable = false,
        unkillable = false,
        death_countdown = 5,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "MAPLOCKED",
        maximumAngleToTarget = 0.5,
        acceleration = 0.24,
        strafingAccelMultiplier = 0.25,
        reverseAccelMultiplier = 0.75,
        inertialCorrection = true,
        isStrafing = false,
        alwaysThrust = false,
        launchDumbThrustSeconds = 0,
        standoffDistance = 3,
        retreatDistance = 2,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 23,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = false,
    },
    doAvoidance = true,
    avoidance = {
        considerationRadius = 4,
        considerStructures = false,
        considerMacroTargetStructures = false,
        drone = 0,
        missile = 0,
        light = 2,
        medium = 3,
        heavy = 8,
        capital = 20,
        titan = 30,
        avoidOnlyClosest = false,
        minimumThreatValue = 10,
        minimumThreatCount = 0,
        panicDistance = 0,
        unpanicDistance = 0,
    },
    isRepulsor = true,
    isNotRepulsed = false,
    repulsion = {
        interactionLayer = 0,
        weightOveride = 0,
        colliderDimensionsOverride = { 0, 0, 0 },
    },
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_AND_MACRO",
            isFriendly = false,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = false,
            ignoreUncapturable = false,
            ignoreNonHealRequester = false,
            targetOnlySpecialType = 0,
            secondsPerScan = 0.5,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 20,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 1,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = 0,
            scoreForAngle = -0.01,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 0,
            perceivedDistanceMin = 0,
            classMultMissile = -1,
            classMultDrone = -1,
            classMultLight = 0.5,
            classMultMedium = 1.5,
            classMultHeavy = 1.1,
            classMultCapital = 1,
            classMultTitan = 0.5,
            shipMultiplier = 1.2,
            structureMultiplier = 0,
            keepTargetMultiplier = 2,
            scoreBandingSize = 0,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "NONE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 2,
    },
}
