return {
    unitName = "yard_capital",
    unitDisplayName = "Yard C25",
    unitTooltip = "- Unique firepower.\n- Capitals require support.",
    unitBlurb = "Capital Shipyard",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "G",
    picture = "1_12010_yard_capital.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012010,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 500,
        cost_energy = 250,
        cost_supply = 35,
        cost_time = 60,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "- - -\n\nThe Mk2 Yard C25's fabrication array and cohension deck can produce the entirety of Kontaal's 400m capital vessel schematics - whether exotic or normal - in times unmatched by any counterpart.\n\nAfter the Yard H9, the ground work was complete. The development of the C25 was an increadible example of coordinated and unified engineering between the many divisions of the Kontaalen fleet development core.\n\nIt's cohension deck is the culmination of all the advancements from the Yard L1, and M4. It's fabrication arrays inherit from the H9, tuned to handle vastly higher material throughputs. And finally, bathed in the dedicated will of Kontaal's most fierce engineers; to utter and total battlescape domination. The C25 burned to life.\n\nThe Ekudon was the first Capital vessel ever designed for the CS25. Predating even the vaguest notion of it's future kin, and many of it's lesser siblings in the medium and heavy class.",
    },
    scale = 5,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_yard_ekudon/01_yard_capital",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "Vortex Cohesion Deck",
            mesh = "vortex Dome/vortex_dome_shell",
            materials = { "mt_vortex_dome_shell_cohesionDeck" },
            position = { 0, 0.0778, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.888167, -0.226044, 0.888167 },
            vortex = true,
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_aegis_bevelBox/01_aegis_bevelBox",
            materials = { "01_MT_Aegis" },
            position = { 0, -0.021, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.5, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0.25, 0, -0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 1, 0.5 },
                },
                {
                    name = "model (1)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0.25, 0, 0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 1, 0.5 },
                },
                {
                    name = "model (2)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { -0.25, 0, -0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 1, 0.5 },
                },
                {
                    name = "model (3)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { -0.25, 0, 0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 1, 0.5 },
                },
                {
                    name = "glow",
                    mesh = "01_yard_ekudon/01_yard_capital",
                    materials = { "01_MT_buildglow_4", "01_MT_buildglow_4", "01_MT_buildglow_4" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 2, 1 },
                },
            },
        },
        {
            name = "Spawnpoint",
            position = { 0, 0.038599, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            spawnerSpawnPoint = {
                code = 0,
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, -0.02, 0 },
        size = { 1, 0.35, 1 },
        orientation = { 0, 0, 0 },
        bevelRadius = 1,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "TITAN",
        health = 25000,
        health_regen_per_second = 15,
        max_regen_frac = 0,
        armour = 10,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013023,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "PRODUCTION",
        ring = { 0, 0 },
        rectangle = { 5, 5 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = true,
    spawner = {
        spawnOffset = { 0, 5, 0 },
        spawnOffsetHeightRandomisation = 1,
        endRotationUseStructureForward = false,
        noUnitGhost = false,
        usesToSelfdestruct = 0,
        simultaniousUnitLimit = 0,
        arrivalData = {
            type = "ARRIVE",
            arrivalDuration = 8,
            approachSpeed = 0.5,
            keepDisabled = false,
        },
    },
    spawnerCapacity = {
        current = 0,
    },
    spawnItems = {
        {
            id = 1011004,
            spawnTime = 150,
            spawnTimeStart = 150,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011020,
            spawnTime = 90,
            spawnTimeStart = 90,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011010,
            spawnTime = 150,
            spawnTimeStart = 150,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011027,
            spawnTime = 150,
            spawnTimeStart = 150,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011015,
            spawnTime = 180,
            spawnTimeStart = 180,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
    },
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
