return {
    unitName = "generator_energy_1x1",
    unitDisplayName = "Katalyst Reactor",
    unitTooltip = "",
    unitBlurb = "Basic <color=#00ffff>Energy</color> generator.",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "R",
    picture = "1_12029_generator_energy_1x1.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012029,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 20,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 15,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "- Matter and space inefficient.",
        description = "- - -\nInfo:\n\nA militarised and overclocked variant of the Pitterson RF88 Katalyst Reactor. Used plentifully throughout the Spance.\n\nFission is the power source of the past, the splitting of the atom now relegated to ugly support roles in unsupervised energy generation. Fusion is the modern standard, but is more demanding in logistics profile then their ancient fission counterparts whom have been optimised to incomprehensible extremes.\n\nAs such the ancient and highly optimised Katalyst Reactor has come to dominate the spancial energy sector. Not only due to the high presense of fissile materials just floating around but due to Kontaalen engineering in ambient-contextual conversion. The Katalyst reactor and it's kin bypass the archaic method of boiling water and spinning a turbine to generate electrical current, by directly utilising heat and radiation gradients to invoke power.\n\nThis is very efficient, but unfortunately such boarderline mythical energy efficiency comes with the rather unfortunate drawback of turning the entire Katalyst Reactor into a bomb. Though not as destructive as a designed nuke, it is none the less rather dangerous.\n\nThere are thankfully very few reported cases of unexpected Katalyst detonations.",
    },
    scale = 1,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_structure_energy_1x1/01_structure_energy_1x1",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_energyGlow" },
    parts = {
        {
            name = "pistons",
            mesh = "01_structure_energy_1x1/01_structure_energy_1x1_piston",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            piston = {
                localDistanceUp = 0.158,
                direction = "Down",
                startProgressFraction = 0,
                duration = 1,
            },
        },
        {
            name = "pistons (2)",
            mesh = "01_structure_energy_1x1/01_structure_energy_1x1_piston",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
            position = { 0, 0, 0 },
            rotation = { -0.000294, 180, 180 },
            scale = { 1, 1, 1 },
            piston = {
                localDistanceUp = 0.158,
                direction = "Down",
                startProgressFraction = 0,
                duration = 1,
            },
        },
        {
            name = "pistons (1)",
            mesh = "01_structure_energy_1x1/01_structure_energy_1x1_piston",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
            position = { 0, 0, 0 },
            rotation = { 0, 90.00005, 0 },
            scale = { 1, 1, 1 },
            piston = {
                localDistanceUp = 0.158,
                direction = "Down",
                startProgressFraction = 0.5,
                duration = 1,
            },
        },
        {
            name = "pistons (3)",
            mesh = "01_structure_energy_1x1/01_structure_energy_1x1_piston",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
            position = { 0, 0, 0 },
            rotation = { 0, 89.99995, 180.0003 },
            scale = { 1, 1, 1 },
            piston = {
                localDistanceUp = 0.158,
                direction = "Down",
                startProgressFraction = 0.5,
                duration = 1,
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "structure_storage_matter/01_structure_storage_matter",
            materials = { "01_MT_Aegis", "01_MT_Aegis", "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.1, 1.1, 1.1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_small",
            mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
            materials = { "01_MT_BaseColour_structure_primary" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "glow",
                    mesh = "01_structure_energy_1x1/01_structure_energy_1x1",
                    materials = { "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Capsule",
        center = { 0, -0.013428, 0 },
        radius = 0.5,
        height = 1.4,
        orientation = { 270, 270, 0 },
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "MEDIUM",
        health = 500,
        health_regen_per_second = 3,
        max_regen_frac = 0,
        armour = 2,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 1,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = true,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = true,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013021,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "ECONOMY",
        ring = { 0, 0 },
        rectangle = { 1, 1 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = true,
    resourceGeneration = {
        matter = 0,
        energy = 0.25,
        phase = 0,
    },
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 1,
    },
}
