return {
    unitName = "control_range_extender",
    unitDisplayName = "Outpost Core",
    unitTooltip = "- Can be <color=#00ffff>placed outside</color> your <color=green>build area</color>.\n(Blue circle must overlap with green tiles)",
    unitBlurb = "Build Area Extender",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "X",
    picture = "",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 6662000,
        factionID = 666,
        macroType = "TRUE",
        cost_matter = 200,
        cost_energy = 200,
        cost_supply = 0,
        cost_time = 40,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "Command and Control is a difficult thing to handle even in a clear exospacial battlefield. But in the Spance it is a nightmare.\n\nThe Local Base Control Node, (LBCN) works as a dedicated command relay.  Hardlinked to it's owner's control grid, and networked to all surrounding buildings with extremely powerful comms systems. It distributes commands, handles reports from local systems, and coordinates material logistics.\n\nThe LBCN contains a rather hefty Base Core specifically dedicated to platform commander neural mirroring, allowing it to somewhat assume what you want at any given time. Often allowing it to reject hostile attempts to hack control and preallocate resources to as-of-yet-ungiven construction tasks.\n\nFinally, it also houses a set of construction drone bays and fleets of logistics haulers that work tirelessly to shift materials around a platform base.",
    },
    scale = 3,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "666_structure_extender_3x3/666_structure_extender_3x3",
    materials = { "666_material_glow_yellowish", "666_material_base_pirate", "666_material_teamColour_pirate", "666_material_chrome", "666_material_teamGlow" },
    parts = {
        {
            name = "Spinner",
            mesh = "666_structure_extender_3x3/666_structure_extender_3x3_spinner",
            materials = { "666_material_base_pirate", "666_material_chrome", "666_material_teamColour_pirate", "666_material_chrome", "666_material_teamGlow" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 30, 0 },
            },
        },
        {
            name = "mechanic_launch",
            position = { -0.236725, 0.000242, 0.133925 },
            rotation = { 90, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 6665015,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = true,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "barrel",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },            
            },
        },
        {
            name = "mechanic_launch",
            position = { -0.236725, 0.000242, -0.133925 },
            rotation = { 90, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 6665015,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = true,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "barrel",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },            
            },
        },
        {
            name = "mechanic_launch",
            position = { -0.236725, -0.000242, 0.133925 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 6665015,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = true,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "barrel",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },            
            },
        },
        {
            name = "mechanic_launch",
            position = { -0.236725, -0.000242, -0.133925 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 6665015,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = true,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "barrel",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },            
            },
        },
        {
            name = "mechanic_launch",
            position = { 0.236725, 0.000242, 0.133925 },
            rotation = { 90, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 6665015,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = true,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "barrel",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },            
            },
        },
        {
            name = "mechanic_launch",
            position = { 0.236725, 0.000242, -0.133925 },
            rotation = { 90, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 6665015,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = true,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "barrel",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },            
            },
        },
        {
            name = "mechanic_launch",
            position = { 0.236725, -0.000242, 0.133925 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 6665015,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = true,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "barrel",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },            
            },
        },
        {
            name = "mechanic_launch",
            position = { 0.236725, -0.000242, -0.133925 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 6665015,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = true,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "barrel",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },            
            },
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "666_material_base_pirate" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_structure_range_extender/01_structure_range_extender",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
    },
    unitCore = true,
    sphereCollider = {
        center = { 0, 0, 0 },
        radius = 0.5,
        isTrigger = false,
    },
    health = {
        unitClass = "CAPITAL",
        health = 4000,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 5,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0.66,
        shredMultiplier = 1.5,
        explosionSFX = 0,
        explosionSFXIntensity = 3,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 5,
        flashSizeOverride = 0,
        forceShockwave = true,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "EXTENDER",
        ring = { 0, 0 },
        rectangle = { 3, 3 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = true,
    influence = {
        strength = { 6, 1 },
        ring = { 0, 9.5 },
        rectangle = { 0, 0 },
        matrixDimensions = { 0, 0 },
    },
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 3,
    },
}
