return {
    unitName = "turret_regorCannon",
    unitDisplayName = "Regor Ripper",
    unitTooltip = "",
    unitBlurb = "Heavy Anti-Swarm Turret",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "J",
    picture = "1_12044_turret_regorCannon.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012044,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 150,
        cost_energy = 50,
        cost_supply = 0,
        cost_time = 20,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Anti-Swarm Turret</color>\nDesigned to hold off Light swarms.\n- Strong against Lights.\n- Decent against Mediums.\n- Poor against 15+ Armour.",
        description = "- - -\n\nThe Shadow Point Eruptor Mk2 is able to sustain incredible rates of fire, and deliver highly effective area-of-effect blasts against lightly armoured targets. However it lacks significantly against thickly armoured targets relative to it's other defencive breathren.\n\nThe SPE2 relies on a miniaturised Regor Kannon from the Yobegregor capital - that is also used by the Valantar heavy. \n\nSome officers of the Kontaalen Fleet Development Core, have asked why it is not possible for Regor Kannons to demonstrate the same armour-shredding efficacy of the Dauwn. Which principally employs point-shadow to great effect against modern vessel armour. \n\nFoundationally the nature of point-shadow makes it exceptionally resistant to normal situations of use. Where point-light can be nicely convinced to play well with the laws of standard physics, happily pretending to appear as a laser to conventional viewing... and stay that way. Getting point-shadow weapons such as the regor kannon to work demands conceding a variety of combat limitations to the stubborn will of nature itself depending on how one wishes to deliver this dark energy to a target.\n\nMuch like the Yobegregor the Regor Ripper's weapons store agitated point-shadow energy. These undulations are then \"released\" and seek out material that has not been polarised to it's same energy-spin. Which all ally forces already are. AKA, hostile forces will now be run down by a shimmering furious pulsation of reality's fibers, and destroyed.",
        weaponInfo = {
            { 1015078, 1, -2 },
        },
    },
    scale = 2,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    displayAreaRadius = 14,
    displayAreaColour = { 1, 0, 0, 0.25098 },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_turretbase_regorSpire/01_turretbase_regorTurret",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_structure_secondary", "01_MT_ShadowGlow", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "Regor Turret",
            position = { 0, 0.5207, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015078,
                turnSpeed = 30,
                turnMode = "Acceleration",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 65,
                    down = 20,
                },
            },
            parts = {
                {
                    name = "body",
                    mesh = "01_turret_regorSpire/01_regorTurret_body",
                    materials = { "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_structure_primary", "01_MT_ShadowGlow", "01_MT_BaseColour_teamGlow" },
                    position = { 0, -0.025, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5696, 0.5696, 0.5696 },
                    turretBody = true,
                },
                {
                    name = "model",
                    mesh = "01_ship_heavy_valantar/01_turret_regor_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_ShadowGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0.0168 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.286441, 0.286441, 0.286441 },
                },
                {
                    name = "barrel",
                    position = { 0.02873, 0.02818, 0.3009 },
                    rotation = { 0, 0, 0 },
                    scale = { 2.169993, 2.169993, 2.169993 },
                    barrel = true,
                },
                {
                    name = "barrel (1)",
                    position = { -0.02873, -0.01891, 0.3462 },
                    rotation = { 0, 0, 0 },
                    scale = { 2.169993, 2.169993, 2.169993 },
                    barrel = true,
                },
                {
                    name = "barrel (2)",
                    position = { 0.02873, -0.01891, 0.3462 },
                    rotation = { 0, 0, 0 },
                    scale = { 2.169993, 2.169993, 2.169993 },
                    barrel = true,
                },
                {
                    name = "barrel (3)",
                    position = { -0.02873, 0.02818, 0.3009 },
                    rotation = { 0, 0, 0 },
                    scale = { 2.169993, 2.169993, 2.169993 },
                    barrel = true,
                },
                {
                    name = "laser_beam (1)",
                    mesh = "cannonflash/cannonflash",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0.0168 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.216999, 0.216999, 0.216999 },
                    weaponVisualConfig = {
                        laserColour = { 0.834769, 0.47451, 1, 1 },
                        intensity = 12,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "laser_beam (2)",
                    mesh = "cannonflash/cannonflash",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0.0168 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.216999, 0.216999, 0.216999 },
                    weaponVisualConfig = {
                        laserColour = { 0.834769, 0.47451, 1, 1 },
                        intensity = 12,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "laser_beam (3)",
                    mesh = "cannonflash/cannonflash",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0.0168 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.216999, 0.216999, 0.216999 },
                    weaponVisualConfig = {
                        laserColour = { 0.834769, 0.47451, 1, 1 },
                        intensity = 12,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "laser_beam (4)",
                    mesh = "cannonflash/cannonflash",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0.0168 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.216999, 0.216999, 0.216999 },
                    weaponVisualConfig = {
                        laserColour = { 0.834769, 0.47451, 1, 1 },
                        intensity = 12,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_turretbase_pulseHowitser_aegis/01_turretbase_pulseHowitser_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0.164, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_turretbase_regorSpire/01_turretbase_regorTurret",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, -0.164, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 1.1, 0.9, 1.1 },
        orientation = { 0, 0, 0 },
        bevelRadius = 0.9,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "HEAVY",
        health = 3000,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 45,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 2.5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 1.2,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "DEFENCE",
        ring = { 0, 0 },
        rectangle = { 2, 2 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = false,
        tier = 2,
    },
}
