return {
    unitName = "missile_swader",
    unitDisplayName = "Swayder",
    unitTooltip = "",
    unitBlurb = "Ordinance Interception Missile",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_14004_missile_swader.png",
    controllable = false,
    unselectable = true,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1014004,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "0",
        requiredLevelForDescription = "",
        tactical = "",
        description = "",
        weaponInfo = {
            { -1, -1, -1 },
            { 1015017, 1, 0 },
        },
    },
    scale = 0.11,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_missile_swader/01_missile_swader",
    materials = { "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_primary" },
    parts = {
        {
            name = "thruster_glow",
            position = { 0, 0, -0.435 },
            rotation = { 0, 0, 0 },
            scale = { 0.25, 0.25, 0.5 },
            thruster = {
                decayTime = 1.5,
                workWhenThrustWithinAngleDegrees = 63,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_ultralowPoly/thrusterplume_utralowpolly",
                    materials = { "01_MT_ThrusterGlow_opaque_bright" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1.5, 1.5, 1.5 },
                },
            },
        },
        {
            name = "warhead",
            position = { 0, 0, 0.11 },
            rotation = { 0, 0, 0 },
            scale = { 0.32205, 0.32205, 0.32205 },
            weapon = {
                weaponID = 1015017,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            scaleModifier = true,
        },
        {
            name = "ParticleEmitter",
            position = { 0, 0, -0.441 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            particleEmitter = {
                particleType = "RIBBON",
                distancePerParticle = 0,
                minSecondsPerParticle = 0,
                ejectionVelocity = -1,
                ejectionVelocityAwayFromEmitter = false,
                requiredVelocityAlignmentDegrees = 0,
                randomRadius = 0,
                randomScaleMinFraction = 0,
                startDisabled = false,
                stateToggleTrigger = "None",
                colourStart = { 0.5, 0.75, 1 },
                colourEnd = { 0.5, 0.5, 0.5 },
                opacity = 0.4,
                scaleStart = 0.03,
                scaleEnd = 0.015,
                lifetime = 0.12,
            },
        },
    },
    unitCore = true,
    physicsShape = {
        shapeType = "Capsule",
        center = { 0, 0, 0 },
        radius = 0.3,
        height = 1,
        orientation = { 0, 0, 0 },
        collisionResponse = "Collide",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "MISSILE",
        health = 8,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 0,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0.3,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0.25,
        phaseBlockFraction = 0,
        lifetime = 5,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "FREE",
        maximumAngleToTarget = 0.2,
        acceleration = 6,
        strafingAccelMultiplier = 1,
        reverseAccelMultiplier = 1,
        inertialCorrection = true,
        isStrafing = false,
        alwaysThrust = false,
        launchDumbThrustSeconds = 0.5,
        standoffDistance = 0,
        retreatDistance = 0,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 201,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = false,
    },
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_ONLY",
            isFriendly = false,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = true,
            ignoreUncapturable = false,
            ignoreNonHealRequester = false,
            targetOnlySpecialType = 0,
            secondsPerScan = 0,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 10,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 1,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = -0.25,
            scoreForAngle = -0.02,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 5,
            perceivedDistanceMin = 0,
            classMultMissile = 0,
            classMultDrone = 0,
            classMultLight = 0,
            classMultMedium = 0,
            classMultHeavy = 0,
            classMultCapital = 0,
            classMultTitan = 0,
            shipMultiplier = 1.2,
            structureMultiplier = 0,
            keepTargetMultiplier = 5,
            scoreBandingSize = 2,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "MISSILE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = true,
    payload = {
        damage = {
            isNondamaging = false,
            instances = 2,
            damage = 22,
            piercing = 0,
            shred = 0,
            heat = 5.5,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        areaEffect = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0.3,
            radiusInner = 0.3,
            waveSteps = 0,
            waveSeconds = 0,
        },
    },
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
