return {
    unitName = "yard_heavy",
    unitDisplayName = "Yard H9",
    unitTooltip = "",
    unitBlurb = "Heavy Shipyard",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "R",
    picture = "1_12005_yard_heavy.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012005,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 100,
        cost_energy = 50,
        cost_supply = 6,
        cost_time = 30,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "- - -\n\nThe Mk8 Yard H9's fabrication array and cohension deck can produce the entirety of Kontaal's 200m heavy vessel schematics - whether exotic or normal - in times unmatched by any counterpart.\n\nAfter the Yard M4 and the development of magnetic fabrication stabilisation, the ground work was laid for the production of even heftier and vaster vessels. The development of the Yard H9 expanded on the technology, including the use of an arrayed point-energy fabrication system.",
    },
    scale = 3,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_yard_heavy/01_yard_heavy",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_structure_secondary" },
    parts = {
        {
            name = "Vortex Cohesion Deck",
            mesh = "vortex Dome/vortex_dome_shell",
            materials = { "mt_vortex_dome_shell_cohesionDeck" },
            position = { 0, 0.095, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.737456, -0.248744, 0.737456 },
            vortex = true,
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_yard_heavy_aegis/01_yard_heavy_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.4, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_yard_heavy/01_yard_heavy",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 2.5, 1 },
                },
            },
        },
        {
            name = "Spawnpoint",
            position = { 0, 0.064331, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            spawnerSpawnPoint = {
                code = 0,
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, -0.02, 0 },
        size = { 0.95, 0.3, 0.95 },
        orientation = { 0, 0, 0 },
        bevelRadius = 1,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "CAPITAL",
        health = 7500,
        health_regen_per_second = 10,
        max_regen_frac = 0,
        armour = 8,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 3,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "PRODUCTION",
        ring = { 0, 0 },
        rectangle = { 3, 3 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = true,
    spawner = {
        spawnOffset = { 0, 4, 0 },
        spawnOffsetHeightRandomisation = 1,
        endRotationUseStructureForward = false,
        noUnitGhost = false,
        usesToSelfdestruct = 0,
        simultaniousUnitLimit = 0,
        arrivalData = {
            type = "ARRIVE",
            arrivalDuration = 4,
            approachSpeed = 0.3,
            keepDisabled = false,
        },
    },
    spawnerCapacity = {
        current = 0,
    },
    spawnItems = {
        {
            id = 1011014,
            spawnTime = 60,
            spawnTimeStart = 60,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011001,
            spawnTime = 90,
            spawnTimeStart = 90,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011009,
            spawnTime = 90,
            spawnTimeStart = 90,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011011,
            spawnTime = 60,
            spawnTimeStart = 60,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011025,
            spawnTime = 90,
            spawnTimeStart = 90,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011026,
            spawnTime = 90,
            spawnTimeStart = 90,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011028,
            spawnTime = 60,
            spawnTimeStart = 60,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
    },
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
