return {
    unitName = "howler_rocket",
    unitDisplayName = "Cluster Rocket",
    unitTooltip = "",
    unitBlurb = "",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_14015_howler_rocket.png",
    controllable = false,
    unselectable = true,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1014015,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "0",
        requiredLevelForDescription = "",
        tactical = "",
        description = "",
        weaponInfo = {
            { 1015068, 1, 1015069 },
        },
    },
    scale = 0.8,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_missile_howler/01_missile_howler",
    materials = { "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamColour" },
    parts = {
        {
            name = "ParticleEmitter",
            position = { 0, 0, -0.411 },
            rotation = { 0, 0, 0 },
            scale = { 0.075725, 0.075725, 0.151438 },
            particleEmitter = {
                particleType = "PARTICLE",
                distancePerParticle = 0.1,
                minSecondsPerParticle = 0,
                ejectionVelocity = -1,
                ejectionVelocityAwayFromEmitter = false,
                requiredVelocityAlignmentDegrees = 0,
                randomRadius = 0.05,
                randomScaleMinFraction = 0,
                startDisabled = false,
                stateToggleTrigger = "None",
                colourStart = { 1, 0.8, 0.6 },
                colourEnd = { 0.5, 0.5, 0.5 },
                opacity = 0.5,
                scaleStart = 0.25,
                scaleEnd = 0.6,
                lifetime = 1.2,
            },
        },
        {
            name = "glow",
            mesh = "thrusterplume_ultralowPoly/thrusterplume_utralowpolly",
            materials = { "01_MT_ThrusterGlow_opaque_bright" },
            position = { 0, 0, -0.405 },
            rotation = { 0, 0, 0 },
            scale = { 0.620288, 0.620288, 1.415397 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
        },
        {
            name = "warhead",
            position = { 0, 0, 0.11 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015068,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            parts = {
                {
                    name = "Barrel",
                    position = { 0, 0, -0.369 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "Barrel (1)",
                    position = { 0, 0, -0.202 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "Barrel (2)",
                    position = { 0, 0, -0.02 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "Barrel (3)",
                    position = { 0, 0, 0.156 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "Barrel (4)",
                    position = { 0, 0, 0.34 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
            },
        },
    },
    unitCore = true,
    physicsShape = {
        shapeType = "Capsule",
        center = { 0, 0, 0.02 },
        radius = 0.219698,
        height = 1.117201,
        orientation = { 0, 0, 0 },
        collisionResponse = "Collide",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "LIGHT",
        health = 200,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 2,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0.75,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 15,
        lifetimeStd = 0,
        explodeOnTimeout = true,
        explosionType = "FLAK",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 1,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "FREE",
        maximumAngleToTarget = 6.28318,
        acceleration = 1.5,
        strafingAccelMultiplier = 0,
        reverseAccelMultiplier = 0,
        inertialCorrection = true,
        isStrafing = false,
        alwaysThrust = false,
        launchDumbThrustSeconds = 1,
        standoffDistance = 0,
        retreatDistance = 0,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 40,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = true,
    },
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_AND_MACRO",
            isFriendly = false,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = false,
            ignoreUncapturable = false,
            ignoreNonHealRequester = false,
            targetOnlySpecialType = 0,
            secondsPerScan = 1,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 30,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 1,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = 0,
            scoreForAngle = -0.01,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 0,
            perceivedDistanceMin = 15,
            classMultMissile = -1,
            classMultDrone = -1,
            classMultLight = 0.1,
            classMultMedium = 0.5,
            classMultHeavy = 1,
            classMultCapital = 1,
            classMultTitan = 1,
            shipMultiplier = 2,
            structureMultiplier = 0,
            keepTargetMultiplier = 5,
            scoreBandingSize = 3,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "MISSILE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
