return {
    unitName = "platform_k90",
    unitDisplayName = "Platform K90",
    unitTooltip = "",
    unitBlurb = "Super Command Platform",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_12041_platform_k90.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012041,
        factionID = 101,
        macroType = "TRUE",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "<color=yellow>Tactical</color>:\n- Limited self defence against drones and lights.\n- Generates Matter, Energy, and Logistics.\n- Tough, can safely draw enemy fire away from weaker base buildings.\n- Detects cloaked units within a large radius.\n\n- - -\nInfo\n\nThe steel core of Kontaalen military control.\n\nDesigned from the ground up following the successed of the K35 and K87, the K90 demonstrates brute mastery over the spancial battlefield.\n\nInbuilt cohesion systems, material refineries, drone bays, fabrication arrays, and shielded command-and-control center, rounded off by a modern graviton reactor. The K-series is able to operate for months on it's own, and deploy the most powerful rapid strike doctrines of the Kontaalen Armada. \n\nFurthermore - though some often forget it - there are people on here.  \n\nModerate sacrifices have been made to incorporate humble crew quarters, recreational spaces, sanitation solutions, and a cultivationary for limited food production. \n\nFinally the 500m wide super structure houses it's principle SAIL Drive, SAIL Interdictor, advanced sensor suites, long range communications systems, and shuttle bays. It is also worth noting the presence of a stocked infantry armoury and the layout of hardened fighting positions able to fend off boarding forces with extreme efficacy.",
        weaponInfo = {
            { 1015082, 1, 0 },
            { 1015054, 12, 0 },
            { 1015064, 4, 1015065 },
        },
    },
    scale = 7,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_platform_7x7/01_platform_7x7",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "explosion_fireball",
            position = { 0.071429, 0, 0.071429 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "LAUNCHER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 8,
                    velocityStd = 2,
                    spreadDegrees = 1800,
                    spreadType = "RANDOM",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0,
                    lifetime = 0,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0,
                        opacity = 0,
                        diameter = 0,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 33010,
                    arrivalData = {
                        type = "NONE",
                        arrivalDuration = 0,
                        approachSpeed = 0,
                        keepDisabled = false,
                    },
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 9999,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 30,
                    shotsPerCycleCurrent = 30,
                    simultaniousShots = 30,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
            parts = {
                {
                    name = "explosion_fireball (1)",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    weapon = {
                        weaponID = 0,
                        turnSpeed = 0,
                        turnMode = "Linear",
                        turnInstant = false,
                        useParentTarget = false,
                        useRootTarget = false,
                        targetRootUnit = false,
                        mountAngles = {
                            left = 0,
                            right = 0,
                            up = 0,
                            down = 0,
                        },
                        weaponData = {
                            weaponType = "LAUNCHER",
                            alwaysfire = true,
                            magdump = false,
                            necrofire = true,
                            active = false,
                            oneuse = false,
                            exemptFromRangeSanityChecks = false,
                            rangeInUnits = 0,
                            maximumAngleToTarget = 0,
                            unitsPerSecond = 6,
                            velocityStd = 2,
                            spreadDegrees = 1800,
                            spreadType = "RANDOM",
                            forceRaycastDirectlyToTarget = false,
                            lockTime = 0,
                            simultaniousObjectLimit = 0,
                            damageData = {
                                isNondamaging = false,
                                instances = 0,
                                damage = 0,
                                piercing = 0,
                                shred = 0,
                                heat = 0,
                                vulnerability = 0,
                                decloak = false,
                                targetingPriorityMultiplier = 0,
                                impulseForce = 0,
                            },
                            selfHealRatio = 0,
                            selfDamage = 0,
                            selfHeat = 0,
                            selfImpulseForce = 0,
                            isNonDecloaking = false,
                            dontFireBelowHealthFraction = 0,
                            resumeFireAboveHealthFraction = 0,
                            dontFireAboveHeatFraction = 0,
                            resumeFireBelowHeatFraction = 0,
                            rangeLimitWhenCloaked = 0,
                            dontFireWhenCloaked = false,
                            isResourceMiner = false,
                            isPiercing = false,
                            piercingThreshold = 0,
                            tractorHoldDistance = 0,
                            isAreaOfEffect = false,
                            aoeData = {
                                friendlyFire = false,
                                maximumDegrees = 0,
                                radiusOuter = 0,
                                radiusInner = 0,
                                waveSteps = 0,
                                waveSeconds = 0,
                            },
                            sfxID = 0,
                            SFXIntensity = 0,
                            sizeInUnits = 0,
                            lifetime = 0,
                            impactSize = 0,
                            impactDuration = 0,
                            disableImpactEffect = false,
                            disableImpactFlash = false,
                            impactColour = { 0, 0, 0, 0 },
                            impactFresnelStrength = 0,
                            disableImpactSizeVariance = false,
                            snapUnitDeathExplosionToImpactPosition = false,
                            impactEffectType = "EXPLOSION",
                            laserDescription = {
                                duration = 0,
                                opacity = 0,
                                diameter = 0,
                                offset = 0,
                                rotateZ = false,
                                rotateY = false,
                                rotateZUpdate = false,
                                rotateYUpdate = false,
                                noRescaleLength = 0,
                                noFade = false,
                                noShrink = false,
                            },
                            lasersPerShot = 0,
                            barrelCount = 0,
                            barrelSpacing = 0,
                            virtualBarrelOffset = { 0, 0, 0 },
                            barrelIndexCurrent = 0,
                            spawnID = 33011,
                            arrivalData = {
                                type = "NONE",
                                arrivalDuration = 0,
                                approachSpeed = 0,
                                keepDisabled = false,
                            },
                            checkForWaypoints = false,
                            ignoreRootVelocity = false,
                            setAutoWaypointTargetToWeaponTarget = false,
                            reloadAmount = 0,
                            secondsPerCycle = 9999,
                            secondsPerCycleCurrent = 0,
                            shotsPerCycle = 30,
                            shotsPerCycleCurrent = 30,
                            simultaniousShots = 30,
                            secondsPerShot = 0,
                            secondsPerShotCurrent = 0,
                        },
                        targeting = {
                            acquisition = {
                                type = "QUADTREE_ONLY",
                                isFriendly = false,
                                isResourceMiner = false,
                                acceptFirstValidTarget = false,
                                pauseIfHasTarget = false,
                                ignoreUncapturable = false,
                                ignoreNonHealRequester = false,
                                targetOnlySpecialType = 0,
                                secondsPerScan = 0,
                                ignoreFullHealth = false,
                                minimumHealth = 0,
                                minimumDistance = 0,
                                maximumDistance = 0.1,
                                maximumAngle = 0,
                                addedPreaimDistance = 0,
                                scoreForDistance = 1,
                                scoreForHealth = 0,
                                scoreForHealthCurrent = 0,
                                scoreForHealthCurrentMissing = 0,
                                scoreForHealthCurrentPercentage = 0,
                                scoreForArmour = 0,
                                scoreForArmourCurrent = 0,
                                scoreForAngle = 0,
                                scoreForMountAngle = 0,
                                perceivedHealthMax = 0,
                                perceivedHealthMin = 0,
                                perceivedArmourMax = 0,
                                perceivedArmourMin = 0,
                                perceivedDistanceMin = 0,
                                classMultMissile = 0,
                                classMultDrone = 0,
                                classMultLight = 0,
                                classMultMedium = 0,
                                classMultHeavy = 0,
                                classMultCapital = 0,
                                classMultTitan = 0,
                                shipMultiplier = 0,
                                structureMultiplier = 0,
                                keepTargetMultiplier = 0,
                                scoreBandingSize = 0,
                            },
                            tracking = {
                                workOnNullEntity = false,
                                positionPredictionType = "NONE",
                                predictionVelocityOveride = 0,
                                predictionAcceleration = 0,
                                doAimingComputation = false,
                                canInvalidateTarget = false,
                                invalidationDistance = 0,
                                invalidationAngle = 0,
                                invalidationVelocityHeadOn = 0,
                            },
                        },
                    },
                },
            },
        },
        {
            name = "detector",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015082,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = true,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 180,
                    down = 180,
                },
            },
            scaleModifier = true,
        },
        {
            name = "Spinner",
            mesh = "01_platform_7x7/01_platform_7x7_core",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_energyGlow" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 90, 0 },
            },
        },
        {
            name = "colliders",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            parts = {
                {
                    name = "collider",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    physicsShape = {
                        shapeType = "Cylinder",
                        center = { 0, 0, 0 },
                        radius = 0.505051,
                        height = 0.265105,
                        orientation = { 270, 270, 0 },
                        bevelRadius = 1,
                        collisionResponse = "None",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_platform_7x7/01_platform_7x7",
            materials = { "01_MT_Aegis", "01_MT_Aegis", "01_MT_Aegis", "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.05, 1.05, 1.05 },
            aegisVisual = true,
        },
        {
            name = "01_prf_pd_turret_sentinel",
            position = { 0, 0.1202, 0.4183 },
            rotation = { 0, 0, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (1)",
            position = { 0, 0.1202, -0.4183 },
            rotation = { 0, 180, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (2)",
            position = { -0.4183, 0.1202, 0 },
            rotation = { 0, 270, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (3)",
            position = { 0.4183, 0.1202, 0 },
            rotation = { 0, 90.00001, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (4)",
            position = { 0.2145, 0.1202, 0.3939 },
            rotation = { 0, 30.00001, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (8)",
            position = { 0.3939, 0.1202, 0.2145 },
            rotation = { 0, 60, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (5)",
            position = { -0.2145, 0.1202, 0.3939 },
            rotation = { 0, 330, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (9)",
            position = { -0.3939, 0.1202, 0.2145 },
            rotation = { 0, 300, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (10)",
            position = { -0.3939, 0.1202, -0.2145 },
            rotation = { 0, 240, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (11)",
            position = { 0.3939, 0.1202, -0.2145 },
            rotation = { 0, 120, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (6)",
            position = { -0.2145, 0.1202, -0.3939 },
            rotation = { 0, 210, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (7)",
            position = { 0.2145, 0.1202, -0.3939 },
            rotation = { 0, 150, 0 },
            scale = { 0.058929, 0.058929, 0.058929 },
            weapon = {
                weaponID = 1015054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "turret_dustpiercer",
            position = { 0.2, 0.1832, 0.2 },
            rotation = { 0, 45, 0 },
            scale = { 0.285714, 0.285714, 0.285714 },
            weapon = {
                weaponID = 1015064,
                turnSpeed = 22.91831,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 110,
                    right = 110,
                    up = 90,
                    down = 10,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_turret_dustPiercer/01_weapon_dustPiercer_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_dustPiercer/01_weapon_dustPiercer_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
                {
                    name = "Barrel",
                    position = { 0, -0.0006, 0.768 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "laser_beam",
                    mesh = "railflash/railflash",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0.768 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    weaponVisualConfig = {
                        laserColour = { 1, 0.632157, 0.47451, 1 },
                        intensity = 9,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "turret_dustpiercer (1)",
            position = { -0.2, 0.1832, 0.2 },
            rotation = { 0, 315, 0 },
            scale = { 0.285714, 0.285714, 0.285714 },
            weapon = {
                weaponID = 1015064,
                turnSpeed = 22.91831,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 110,
                    right = 110,
                    up = 90,
                    down = 10,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_turret_dustPiercer/01_weapon_dustPiercer_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_dustPiercer/01_weapon_dustPiercer_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
                {
                    name = "Barrel",
                    position = { 0, -0.0006, 0.768 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "laser_beam",
                    mesh = "railflash/railflash",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0.768 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    weaponVisualConfig = {
                        laserColour = { 1, 0.632157, 0.47451, 1 },
                        intensity = 9,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "turret_dustpiercer (2)",
            position = { -0.2, 0.1832, -0.2 },
            rotation = { 0, 225, 0 },
            scale = { 0.285714, 0.285714, 0.285714 },
            weapon = {
                weaponID = 1015064,
                turnSpeed = 22.91831,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 110,
                    right = 110,
                    up = 90,
                    down = 10,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_turret_dustPiercer/01_weapon_dustPiercer_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_dustPiercer/01_weapon_dustPiercer_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
                {
                    name = "Barrel",
                    position = { 0, -0.0006, 0.768 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "laser_beam",
                    mesh = "railflash/railflash",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0.768 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    weaponVisualConfig = {
                        laserColour = { 1, 0.632157, 0.47451, 1 },
                        intensity = 9,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "turret_dustpiercer (3)",
            position = { 0.2, 0.1832, -0.2 },
            rotation = { 0, 135, 0 },
            scale = { 0.285714, 0.285714, 0.285714 },
            weapon = {
                weaponID = 1015064,
                turnSpeed = 22.91831,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 110,
                    right = 110,
                    up = 90,
                    down = 10,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_turret_dustPiercer/01_weapon_dustPiercer_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_dustPiercer/01_weapon_dustPiercer_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
                {
                    name = "Barrel",
                    position = { 0, -0.0006, 0.768 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "laser_beam",
                    mesh = "railflash/railflash",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0.768 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    weaponVisualConfig = {
                        laserColour = { 1, 0.632157, 0.47451, 1 },
                        intensity = 9,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    health = {
        unitClass = "TITAN",
        health = 40000,
        health_regen_per_second = 50,
        max_regen_frac = 0,
        armour = 40,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = true,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 15,
        flashSizeOverride = 14,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = true,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013023,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0.1,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "NONE",
        ring = { 0, 0 },
        rectangle = { 0, 0 },
        matrixDimensions = { 7, 7 },
        matrix = { 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0 },
    },
    structureIgnoreInfluenceControl = true,
    isInfluencer = true,
    influence = {
        strength = { 30, 10 },
        ring = { 0, 14.5 },
        rectangle = { 0, 0 },
        matrixDimensions = { 0, 0 },
    },
    isSpawner = false,
    isGenerator = true,
    resourceGeneration = {
        matter = 8,
        energy = 4,
        phase = 0,
    },
    isCapacitor = true,
    resourceCapacity = {
        matter = 1000,
        energy = 500,
        phase = 0,
        logistics = 200,
    },
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = true,
    commandType = "CENTRAL",
}
