return {
    unitName = "bullet_untresnafol_SPECIAL",
    unitDisplayName = "Vokadeer",
    unitTooltip = "",
    unitBlurb = "",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_14005_bullet_untresnafol_SPECIAL.png",
    controllable = false,
    unselectable = true,
    untargetable = true,
    unhittable = true,
    data = {
        typeID = 1014005,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "0",
        requiredLevelForDescription = "",
        tactical = "",
        description = "",
        weaponInfo = {
            { 1015062, 1, 0 },
        },
    },
    scale = 0.32,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    parts = {
        {
            name = "warhead",
            position = { 0, 0, 0.337 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015062,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            scaleModifier = true,
        },
        {
            name = "model",
            mesh = "01_bullet_untresnafol_SPECIAL/01_bullet_untresnafol_SPECIAL",
            materials = { "01_MT_BaseColour_ship_primary", "01_MT_Ghost_TeamColour", "MT_ThrusterGlowBlueOpaque", "01_MT_BaseColour_teamGlow" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 0, 120 },
            },
            parts = {
                {
                    name = "ParticleEmitter",
                    position = { 0, 0, -0.45 },
                    rotation = { 0, 0, 0 },
                    scale = { 0, 0, 0 },
                    particleEmitter = {
                        particleType = "PARTICLE",
                        distancePerParticle = 0.05,
                        minSecondsPerParticle = 0,
                        ejectionVelocity = 0,
                        ejectionVelocityAwayFromEmitter = false,
                        requiredVelocityAlignmentDegrees = 0,
                        randomRadius = 0.1,
                        randomScaleMinFraction = 0.5,
                        startDisabled = false,
                        stateToggleTrigger = "None",
                        colourStart = { 1, 1, 1 },
                        colourEnd = { 0.5, 0.5, 0.5 },
                        opacity = 0.3,
                        scaleStart = 0.4,
                        scaleEnd = 0.2,
                        lifetime = 2,
                    },
                },
            },
        },
        {
            name = "glow",
            mesh = "01_bullet_gregor/01_bullet_gregor_thruster",
            materials = { "01_material_plasma_lantra" },
            position = { 0, 0, -0.295 },
            rotation = { 0, 0, 0 },
            scale = { 2.0544, 2.0544, 6.557866 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 0, -500 },
            },
        },
        {
            name = "warning_line",
            mesh = "taperbeam/taperbeam_single",
            materials = { "MT_WarningLine" },
            position = { 0, 0, 1.969 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 40 },
            parts = {
                {
                    name = "line",
                    mesh = "taperbeam/taperbeam_single",
                    materials = { "MT_WarningLine" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 2 },
                },
                {
                    name = "line (1)",
                    mesh = "taperbeam/taperbeam_single",
                    materials = { "MT_WarningLine" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 3 },
                },
                {
                    name = "line (2)",
                    mesh = "taperbeam/taperbeam_single",
                    materials = { "MT_WarningLine" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 4 },
                },
                {
                    name = "line (3)",
                    mesh = "taperbeam/taperbeam_single",
                    materials = { "MT_WarningLine" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 5 },
                },
                {
                    name = "line (4)",
                    mesh = "taperbeam/taperbeam_single",
                    materials = { "MT_WarningLine" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 6 },
                },
                {
                    name = "line (5)",
                    mesh = "taperbeam/taperbeam_single",
                    materials = { "MT_WarningLine" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 7 },
                },
                {
                    name = "line (6)",
                    mesh = "taperbeam/taperbeam_single",
                    materials = { "MT_WarningLine" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 8 },
                },
                {
                    name = "line_core",
                    mesh = "taperbeam/taperbeam_single",
                    materials = { "MT_WarningLine_bright" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.1, 0.1, 8 },
                },
                {
                    name = "warning_line_start",
                    mesh = "taperbeam/taperbeam_single",
                    materials = { "MT_WarningLine" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 179.9999, 0 },
                    scale = { 1, 1, 0.003 },
                    parts = {
                        {
                            name = "line",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_WarningLine" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 2 },
                        },
                        {
                            name = "line (1)",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_WarningLine" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 3 },
                        },
                        {
                            name = "line (2)",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_WarningLine" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 4 },
                        },
                        {
                            name = "line (3)",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_WarningLine" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 5 },
                        },
                        {
                            name = "line (4)",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_WarningLine" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 6 },
                        },
                        {
                            name = "line (5)",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_WarningLine" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 7 },
                        },
                        {
                            name = "line (6)",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_WarningLine" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 8 },
                        },
                        {
                            name = "line_core",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_WarningLine_bright" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.1, 0.1, 8 },
                        },
                    },
                },
            },
        },
    },
    unitCore = true,
    health = {
        unitClass = "NONE",
        health = 10000,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 100,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 4,
        explosionSFXIntensity = 15,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 350,
        lifetimeStd = 0,
        explodeOnTimeout = true,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 3,
        flashSizeOverride = 0,
        forceShockwave = true,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
