return {
    unitName = "medium_alkanador",
    unitDisplayName = "Alkanador",
    unitTooltip = "",
    unitBlurb = "Medium Fleet Defence",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "K",
    picture = "1_11002_medium_alkanador.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1011002,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Point Defence</color>\nDesigned to protect Mediums and Heavies.\n- Strong against Missiles / Drones.\n- Decent against Lights.\n- Poor against 10+ Armour.",
        description = "- - -\nAL KANA DOR\nAnother Light More\n\nA common and exceptionally effective point-defence vessel, geared towards mitigating hostile drone swarms and missile salvos.\n\nThe Alkanador's PD lasers are exceptionally agile, rated as among the most effective rotary tracker designs in the Armada. In the earliest days of the Spance, it served as the mainline medium vessel of the Armada. But was rapidly phased out upon the development of the Otorell, and the refining of the Alakandor's weaponry into point-defence.\n\nThe Alkanador was the 3rd design completed, backing up the Tolly and Kataolosteer in the Armada roster. Used to great effect against Crowe's Vaalkorei drone doctrine during the First Spancial War. It's weapons were overcharged, unstable, able to rip through fleets of light vessels like paper. It was in effect, a laser machine gun platform. However, that was phased out due to excessive production complexity demands.",
        weaponInfo = {
            { 1015003, 4, 0 },
        },
    },
    scale = 1,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 0.5,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_ship_medium_alkanador/01_ship_medium_alkanador",
    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_teamColour" },
    parts = {
        {
            name = "thruster_glow",
            position = { 0, 0, -0.47 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            thruster = {
                decayTime = 1,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.2965, 0.2965, 0.486497 },
                },
            },
        },
        {
            name = "deathflash",
            position = { -0.001, 0.17, -0.264 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "SPARKLER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0.4,
                    lifetime = 0.32,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0.32,
                        opacity = 0,
                        diameter = 0.4,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 2,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "deathflash (1)",
            position = { 0.156, 0.122, 0.219 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "SPARKLER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0.18,
                    lifetime = 0.12,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0.12,
                        opacity = 0,
                        diameter = 0.18,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 2,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "deathflash (2)",
            position = { -0.028, 0.151, 0.06 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "SPARKLER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0.22,
                    lifetime = 0.24,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0.24,
                        opacity = 0,
                        diameter = 0.22,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 1,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "deathflash (3)",
            position = { -0.264, 0.101, -0.18 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "SPARKLER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    velocityStd = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0.14,
                    lifetime = 0.1,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0.1,
                        opacity = 0,
                        diameter = 0.14,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 0.8,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_ship_medium_alkanador_aegis/01_ship_medium_alkonodor_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "turret_right",
            position = { 0.4, 0, -0.108 },
            rotation = { 0, 0, 270 },
            scale = { 0.20295, 0.20295, 0.20295 },
            weapon = {
                weaponID = 1015003,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 90,
                    down = 20,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "barrel",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_defender_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_defender_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "turret_top",
            position = { 0, 0.22, -0.1631 },
            rotation = { 0, 0, 0 },
            scale = { 0.20295, 0.20295, 0.20295 },
            weapon = {
                weaponID = 1015003,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 90,
                    down = 10,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "barrel",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_defender_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_defender_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "turret_left",
            position = { -0.4, 0, -0.108 },
            rotation = { 0, 0, 90 },
            scale = { 0.20295, 0.20295, 0.20295 },
            weapon = {
                weaponID = 1015003,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 90,
                    down = 20,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "barrel",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_defender_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body (1)",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_defender_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "turret_bottom",
            position = { 0, -0.22, -0.1631 },
            rotation = { 0, 0, 180 },
            scale = { 0.20295, 0.20295, 0.20295 },
            weapon = {
                weaponID = 1015003,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 90,
                    down = 10,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "barrel",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_defender_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_defender_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.5,
        angularDamping = 0.5,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 0.5, 0.227586, 1 },
        orientation = { 0, 0, 0 },
        bevelRadius = 6.05,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    ghostMesh = "01_ship_medium_alkanador/01_ship_medium_alkanador",
    ghostMaterials = { "01_MT_BaseColour_ship_primary", "01_MT_Glow_dead", "01_MT_BaseColour_ship_secondary", "01_MT_Ghost_TeamColour" },
    ghostParts = {
        {
            name = "glow",
            mesh = "01_ship_medium_alkanador/01_ship_medium_alkanador",
            materials = { "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
        },
    },
    health = {
        unitClass = "MEDIUM",
        health = 500,
        health_regen_per_second = 2,
        max_regen_frac = 0,
        armour = 10,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 1,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0.9,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013021,
        invulnerable = false,
        unkillable = false,
        death_countdown = 2.5,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "MAPLOCKED",
        maximumAngleToTarget = 0.5,
        acceleration = 0.18,
        strafingAccelMultiplier = 0.25,
        reverseAccelMultiplier = 0.5,
        inertialCorrection = true,
        isStrafing = false,
        alwaysThrust = false,
        launchDumbThrustSeconds = 0,
        standoffDistance = 6.75,
        retreatDistance = 5.5,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 20,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = false,
    },
    doAvoidance = true,
    avoidance = {
        considerationRadius = 6,
        considerStructures = false,
        considerMacroTargetStructures = false,
        drone = 0,
        missile = 2,
        light = 2.5,
        medium = 10,
        heavy = 15,
        capital = 20,
        titan = 30,
        avoidOnlyClosest = false,
        minimumThreatValue = 10,
        minimumThreatCount = 0,
        panicDistance = 0,
        unpanicDistance = 0,
    },
    isRepulsor = true,
    isNotRepulsed = false,
    repulsion = {
        interactionLayer = 0,
        weightOveride = 0,
        colliderDimensionsOverride = { 0, 0, 0 },
    },
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_AND_MACRO",
            isFriendly = false,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = false,
            ignoreUncapturable = false,
            ignoreNonHealRequester = false,
            targetOnlySpecialType = 0,
            secondsPerScan = 0.5,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 20,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 1,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = 0,
            scoreForAngle = 0,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 0,
            perceivedDistanceMin = 0,
            classMultMissile = -1,
            classMultDrone = -1,
            classMultLight = 1,
            classMultMedium = 1,
            classMultHeavy = 1,
            classMultCapital = 1,
            classMultTitan = 1,
            shipMultiplier = 0,
            structureMultiplier = 0,
            keepTargetMultiplier = 1.1,
            scoreBandingSize = 0,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "NONE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 2,
    },
}
