return {
    unitName = "titan_soulwarden_fore",
    unitDisplayName = "Soul Warden Fore",
    unitTooltip = "",
    unitBlurb = "",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_11022_titan_soulwarden_fore.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1011022,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "HIDDEN",
        requiredLevelForVisible = "2009",
        requiredLevelForDescription = "2009",
        tactical = "",
        description = "<color=red>[ WARNING ]</color>\nLittle to no recorded combat information. Tactical approximation:\n\n<color=yellow>Tactical</color>\n+ Mobile Fleet Factory\n+ Dominating Anti-Capital Armerments\n+ Excessive fleet support.\n+ Enormous.\n+ Unique\n\n\n[Halt's Note]\n\nSo. You know how the Kontaalen are a massive galactic nation with a war obsession? Yeah. Yeah.\n\nThis thing is serious, a proper war titan designed to single handedly dominate entire regions of the Spance. It is among the few reasons Crowe was willing to have peace with the Kontaalen for a time.\n\nNo one has dueled the Soul Warden, apart from Crowe's most elite commanders. And they don't win, they just survive. The Kontaalen don't let this thing out for nothing, and I assure you one of the fleetsouls are onboard.\n\nThere's rumors that there are three of these things. Personally, I hope that's just rumor.\n\nDO NOT, and I'm saying this against future me also. DO NOT, EVER, engage the Soul Warden without one hell of a good plan!",
        weaponInfo = {
            { 1015079, 4, 0 },
        },
    },
    scale = 10.15748,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 0.3,
        lengthMultiplier = 0.6,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_hero_wesnett_soulwarden/01_titan_soulWarden_fore",
    materials = { "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "scaler",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.498895, 0.498895, 0.498895 },
            parts = {
                {
                    name = "Colliders",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 3.937985, 3.937985, 3.937985 },
                    physicsShape = {
                        shapeType = "Box",
                        center = { 0, 0, 0.007907 },
                        size = { 0.409757, 0.07058, 0.219 },
                        orientation = { 0, 0, 0 },
                        bevelRadius = 0.352118,
                        collisionResponse = "None",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
                {
                    name = "turret - Korevnavesor",
                    mesh = "01_hero_wesnett_soulwarden/01_hero_soulWarden_korevnasor_gun",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { -0.506812, 0.287724, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 4.652803, 4.652805, 4.652805 },
                    weapon = {
                        weaponID = 1015079,
                        turnSpeed = 20,
                        turnMode = "Linear",
                        turnInstant = false,
                        useParentTarget = false,
                        useRootTarget = false,
                        targetRootUnit = false,
                        mountAngles = {
                            left = 135,
                            right = 55,
                            up = 30,
                            down = 15,
                        },
                    },
                    parts = {
                        {
                            name = "Body",
                            mesh = "01_hero_wesnett_soulwarden/01_hero_soulWarden_korevnasor_body",
                            materials = { "01_MT_BaseColour_ship_primary" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 1 },
                            turretBody = true,
                        },
                        {
                            name = "barrel",
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 1.077001 },
                            barrel = true,
                        },
                        {
                            name = "laser_beam",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.003871, 0.003871, 0.003871 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.477419, 0.1, 1 },
                                intensity = 4,
                                useWeaponLaserDescription = true,
                                laserDescription = {
                                    duration = 0,
                                    opacity = 0,
                                    diameter = 0,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (1)",
                            mesh = "railflash/railflash",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 1.077001 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.564136, 0.25, 1 },
                                intensity = 5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 0.8,
                                    diameter = 0.45,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = true,
                                    rotateYUpdate = false,
                                    noRescaleLength = 60,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (2)",
                            mesh = "disruptorbeam/disruptor_beam_thin",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.001517, 0.001517, 0.008222 },
                            weaponVisualConfig = {
                                laserColour = { 0.343137, 0.638823, 0.980392, 1 },
                                intensity = 2.5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 1,
                                    diameter = 0.01,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = true,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (3)",
                            mesh = "ringflash/ringflash3",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 0.223349 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.564136, 0.25, 1 },
                                intensity = 5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.15,
                                    opacity = 0.8,
                                    diameter = 0.5,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 3,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (4)",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.003871, 0.003871, 0.003871 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.448253, 0.05, 1 },
                                intensity = 15,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 1,
                                    diameter = 0.005,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (5)",
                            mesh = "lightningarc/lightning_arc",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.017891, 0.017891, 0.047868 },
                            weaponVisualConfig = {
                                laserColour = { 0.637255, 0.79222, 0.980392, 1 },
                                intensity = 3,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.15,
                                    opacity = 1,
                                    diameter = 0.04,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 2.5,
                                    noFade = false,
                                    noShrink = true,
                                },
                            },
                            scaleModifier = true,
                        },
                    },
                },
                {
                    name = "turret - Korevnavesor (1)",
                    mesh = "01_hero_wesnett_soulwarden/01_hero_soulWarden_korevnasor_gun",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0.506812, 0.287724, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 4.652803, 4.652805, 4.652805 },
                    weapon = {
                        weaponID = 1015079,
                        turnSpeed = 20,
                        turnMode = "Linear",
                        turnInstant = false,
                        useParentTarget = false,
                        useRootTarget = false,
                        targetRootUnit = false,
                        mountAngles = {
                            left = 55,
                            right = 135,
                            up = 30,
                            down = 15,
                        },
                    },
                    parts = {
                        {
                            name = "Body",
                            mesh = "01_hero_wesnett_soulwarden/01_hero_soulWarden_korevnasor_body",
                            materials = { "01_MT_BaseColour_ship_primary" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 1 },
                            turretBody = true,
                        },
                        {
                            name = "barrel",
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 1.077001 },
                            barrel = true,
                        },
                        {
                            name = "laser_beam",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.003871, 0.003871, 0.003871 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.477419, 0.1, 1 },
                                intensity = 4,
                                useWeaponLaserDescription = true,
                                laserDescription = {
                                    duration = 0,
                                    opacity = 0,
                                    diameter = 0,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (1)",
                            mesh = "railflash/railflash",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 1.077001 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.564136, 0.25, 1 },
                                intensity = 5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 0.8,
                                    diameter = 0.45,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = true,
                                    rotateYUpdate = false,
                                    noRescaleLength = 60,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (2)",
                            mesh = "disruptorbeam/disruptor_beam_thin",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.001517, 0.001517, 0.008222 },
                            weaponVisualConfig = {
                                laserColour = { 0.343137, 0.638823, 0.980392, 1 },
                                intensity = 2.5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 1,
                                    diameter = 0.01,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = true,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (3)",
                            mesh = "ringflash/ringflash3",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 0.223349 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.564136, 0.25, 1 },
                                intensity = 5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.15,
                                    opacity = 0.8,
                                    diameter = 0.5,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 3,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (4)",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.003871, 0.003871, 0.003871 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.448253, 0.05, 1 },
                                intensity = 15,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 1,
                                    diameter = 0.005,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (5)",
                            mesh = "lightningarc/lightning_arc",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.017891, 0.017891, 0.047868 },
                            weaponVisualConfig = {
                                laserColour = { 0.637255, 0.79222, 0.980392, 1 },
                                intensity = 3,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.15,
                                    opacity = 1,
                                    diameter = 0.04,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 2.5,
                                    noFade = false,
                                    noShrink = true,
                                },
                            },
                            scaleModifier = true,
                        },
                    },
                },
                {
                    name = "turret - Korevnavesor (2)",
                    mesh = "01_hero_wesnett_soulwarden/01_hero_soulWarden_korevnasor_gun",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { -0.506812, -0.287724, 0 },
                    rotation = { 0, 0, 180 },
                    scale = { 4.652803, 4.652805, 4.652805 },
                    weapon = {
                        weaponID = 1015079,
                        turnSpeed = 20,
                        turnMode = "Linear",
                        turnInstant = false,
                        useParentTarget = false,
                        useRootTarget = false,
                        targetRootUnit = false,
                        mountAngles = {
                            left = 135,
                            right = 55,
                            up = 30,
                            down = 15,
                        },
                    },
                    parts = {
                        {
                            name = "Body",
                            mesh = "01_hero_wesnett_soulwarden/01_hero_soulWarden_korevnasor_body",
                            materials = { "01_MT_BaseColour_ship_primary" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 1 },
                            turretBody = true,
                        },
                        {
                            name = "barrel",
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 1.077001 },
                            barrel = true,
                        },
                        {
                            name = "laser_beam",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.003871, 0.003871, 0.003871 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.477419, 0.1, 1 },
                                intensity = 4,
                                useWeaponLaserDescription = true,
                                laserDescription = {
                                    duration = 0,
                                    opacity = 0,
                                    diameter = 0,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (1)",
                            mesh = "railflash/railflash",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 1.077001 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.564136, 0.25, 1 },
                                intensity = 5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 0.8,
                                    diameter = 0.45,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = true,
                                    rotateYUpdate = false,
                                    noRescaleLength = 60,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (2)",
                            mesh = "disruptorbeam/disruptor_beam_thin",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.001517, 0.001517, 0.008222 },
                            weaponVisualConfig = {
                                laserColour = { 0.343137, 0.638823, 0.980392, 1 },
                                intensity = 2.5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 1,
                                    diameter = 0.01,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = true,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (3)",
                            mesh = "ringflash/ringflash3",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 0.223349 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.564136, 0.25, 1 },
                                intensity = 5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.15,
                                    opacity = 0.8,
                                    diameter = 0.5,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 3,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (4)",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.003871, 0.003871, 0.003871 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.448253, 0.05, 1 },
                                intensity = 15,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 1,
                                    diameter = 0.005,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (5)",
                            mesh = "lightningarc/lightning_arc",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.017891, 0.017891, 0.047868 },
                            weaponVisualConfig = {
                                laserColour = { 0.637255, 0.79222, 0.980392, 1 },
                                intensity = 3,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.15,
                                    opacity = 1,
                                    diameter = 0.04,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 2.5,
                                    noFade = false,
                                    noShrink = true,
                                },
                            },
                            scaleModifier = true,
                        },
                    },
                },
                {
                    name = "turret - Korevnavesor (3)",
                    mesh = "01_hero_wesnett_soulwarden/01_hero_soulWarden_korevnasor_gun",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0.506812, -0.287724, 0 },
                    rotation = { 0, 0, 180 },
                    scale = { 4.652803, 4.652805, 4.652805 },
                    weapon = {
                        weaponID = 1015079,
                        turnSpeed = 20,
                        turnMode = "Linear",
                        turnInstant = false,
                        useParentTarget = false,
                        useRootTarget = false,
                        targetRootUnit = false,
                        mountAngles = {
                            left = 55,
                            right = 135,
                            up = 30,
                            down = 15,
                        },
                    },
                    parts = {
                        {
                            name = "Body",
                            mesh = "01_hero_wesnett_soulwarden/01_hero_soulWarden_korevnasor_body",
                            materials = { "01_MT_BaseColour_ship_primary" },
                            position = { 0, 0, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 1 },
                            turretBody = true,
                        },
                        {
                            name = "barrel",
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 1.077001 },
                            barrel = true,
                        },
                        {
                            name = "laser_beam",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.003871, 0.003871, 0.003871 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.477419, 0.1, 1 },
                                intensity = 4,
                                useWeaponLaserDescription = true,
                                laserDescription = {
                                    duration = 0,
                                    opacity = 0,
                                    diameter = 0,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (1)",
                            mesh = "railflash/railflash",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 1.077001 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.564136, 0.25, 1 },
                                intensity = 5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 0.8,
                                    diameter = 0.45,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = true,
                                    rotateYUpdate = false,
                                    noRescaleLength = 60,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (2)",
                            mesh = "disruptorbeam/disruptor_beam_thin",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.001517, 0.001517, 0.008222 },
                            weaponVisualConfig = {
                                laserColour = { 0.343137, 0.638823, 0.980392, 1 },
                                intensity = 2.5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 1,
                                    diameter = 0.01,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = true,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (3)",
                            mesh = "ringflash/ringflash3",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.198644, 0.198644, 0.223349 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.564136, 0.25, 1 },
                                intensity = 5,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.15,
                                    opacity = 0.8,
                                    diameter = 0.5,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 3,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (4)",
                            mesh = "taperbeam/taperbeam_single",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.003871, 0.003871, 0.003871 },
                            weaponVisualConfig = {
                                laserColour = { 1, 0.448253, 0.05, 1 },
                                intensity = 15,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.3,
                                    opacity = 1,
                                    diameter = 0.005,
                                    offset = 0,
                                    rotateZ = false,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 0,
                                    noFade = false,
                                    noShrink = false,
                                },
                            },
                            scaleModifier = true,
                        },
                        {
                            name = "laser_beam (5)",
                            mesh = "lightningarc/lightning_arc",
                            materials = { "MT_LaserBeam" },
                            position = { 0, 0, 0.06439 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.017891, 0.017891, 0.047868 },
                            weaponVisualConfig = {
                                laserColour = { 0.637255, 0.79222, 0.980392, 1 },
                                intensity = 3,
                                useWeaponLaserDescription = false,
                                laserDescription = {
                                    duration = 0.15,
                                    opacity = 1,
                                    diameter = 0.04,
                                    offset = 0,
                                    rotateZ = true,
                                    rotateY = false,
                                    rotateZUpdate = false,
                                    rotateYUpdate = false,
                                    noRescaleLength = 2.5,
                                    noFade = false,
                                    noShrink = true,
                                },
                            },
                            scaleModifier = true,
                        },
                    },
                },
                {
                    name = "fireball",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.789342, 0.789342, 0.789342 },
                    weapon = {
                        weaponID = 0,
                        turnSpeed = 0,
                        turnMode = "Linear",
                        turnInstant = false,
                        useParentTarget = false,
                        useRootTarget = false,
                        targetRootUnit = false,
                        mountAngles = {
                            left = 0,
                            right = 0,
                            up = 0,
                            down = 0,
                        },
                        weaponData = {
                            weaponType = "LAUNCHER",
                            alwaysfire = true,
                            magdump = false,
                            necrofire = true,
                            active = false,
                            oneuse = false,
                            exemptFromRangeSanityChecks = false,
                            rangeInUnits = 0,
                            maximumAngleToTarget = 0,
                            unitsPerSecond = 3,
                            velocityStd = 1,
                            spreadDegrees = 1800,
                            spreadType = "RANDOM",
                            forceRaycastDirectlyToTarget = false,
                            lockTime = 0,
                            simultaniousObjectLimit = 0,
                            damageData = {
                                isNondamaging = false,
                                instances = 0,
                                damage = 0,
                                piercing = 0,
                                shred = 0,
                                heat = 0,
                                vulnerability = 0,
                                decloak = false,
                                targetingPriorityMultiplier = 0,
                                impulseForce = 0,
                            },
                            selfHealRatio = 0,
                            selfDamage = 0,
                            selfHeat = 0,
                            selfImpulseForce = 0,
                            isNonDecloaking = false,
                            dontFireBelowHealthFraction = 0,
                            resumeFireAboveHealthFraction = 0,
                            dontFireAboveHeatFraction = 0,
                            resumeFireBelowHeatFraction = 0,
                            rangeLimitWhenCloaked = 0,
                            dontFireWhenCloaked = false,
                            isResourceMiner = false,
                            isPiercing = false,
                            piercingThreshold = 0,
                            tractorHoldDistance = 0,
                            isAreaOfEffect = false,
                            aoeData = {
                                friendlyFire = false,
                                maximumDegrees = 0,
                                radiusOuter = 0,
                                radiusInner = 0,
                                waveSteps = 0,
                                waveSeconds = 0,
                            },
                            sfxID = 0,
                            SFXIntensity = 0,
                            sizeInUnits = 0,
                            lifetime = 0,
                            impactSize = 0,
                            impactDuration = 0,
                            disableImpactEffect = false,
                            disableImpactFlash = false,
                            impactColour = { 0, 0, 0, 0 },
                            impactFresnelStrength = 0,
                            disableImpactSizeVariance = false,
                            snapUnitDeathExplosionToImpactPosition = false,
                            impactEffectType = "EXPLOSION",
                            laserDescription = {
                                duration = 0,
                                opacity = 0,
                                diameter = 0,
                                offset = 0,
                                rotateZ = false,
                                rotateY = false,
                                rotateZUpdate = false,
                                rotateYUpdate = false,
                                noRescaleLength = 0,
                                noFade = false,
                                noShrink = false,
                            },
                            lasersPerShot = 0,
                            barrelCount = 0,
                            barrelSpacing = 0,
                            virtualBarrelOffset = { 0, 0, 0 },
                            barrelIndexCurrent = 0,
                            spawnID = 33011,
                            arrivalData = {
                                type = "NONE",
                                arrivalDuration = 0,
                                approachSpeed = 0,
                                keepDisabled = false,
                            },
                            checkForWaypoints = false,
                            ignoreRootVelocity = false,
                            setAutoWaypointTargetToWeaponTarget = false,
                            reloadAmount = 0,
                            secondsPerCycle = 9999,
                            secondsPerCycleCurrent = 0,
                            shotsPerCycle = 30,
                            shotsPerCycleCurrent = 30,
                            simultaniousShots = 30,
                            secondsPerShot = 0,
                            secondsPerShotCurrent = 0,
                        },
                        targeting = {
                            acquisition = {
                                type = "QUADTREE_ONLY",
                                isFriendly = false,
                                isResourceMiner = false,
                                acceptFirstValidTarget = false,
                                pauseIfHasTarget = false,
                                ignoreUncapturable = false,
                                ignoreNonHealRequester = false,
                                targetOnlySpecialType = 0,
                                secondsPerScan = 0,
                                ignoreFullHealth = false,
                                minimumHealth = 0,
                                minimumDistance = 0,
                                maximumDistance = 0.1,
                                maximumAngle = 0,
                                addedPreaimDistance = 0,
                                scoreForDistance = 1,
                                scoreForHealth = 0,
                                scoreForHealthCurrent = 0,
                                scoreForHealthCurrentMissing = 0,
                                scoreForHealthCurrentPercentage = 0,
                                scoreForArmour = 0,
                                scoreForArmourCurrent = 0,
                                scoreForAngle = 0,
                                scoreForMountAngle = 0,
                                perceivedHealthMax = 0,
                                perceivedHealthMin = 0,
                                perceivedArmourMax = 0,
                                perceivedArmourMin = 0,
                                perceivedDistanceMin = 0,
                                classMultMissile = 0,
                                classMultDrone = 0,
                                classMultLight = 0,
                                classMultMedium = 0,
                                classMultHeavy = 0,
                                classMultCapital = 0,
                                classMultTitan = 0,
                                shipMultiplier = 0,
                                structureMultiplier = 0,
                                keepTargetMultiplier = 0,
                                scoreBandingSize = 0,
                            },
                            tracking = {
                                workOnNullEntity = false,
                                positionPredictionType = "NONE",
                                predictionVelocityOveride = 0,
                                predictionAcceleration = 0,
                                doAimingComputation = false,
                                canInvalidateTarget = false,
                                invalidationDistance = 0,
                                invalidationAngle = 0,
                                invalidationVelocityHeadOn = 0,
                            },
                        },
                    },
                },
                {
                    name = "fireball (1)",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.789342, 0.789342, 0.789342 },
                    weapon = {
                        weaponID = 0,
                        turnSpeed = 0,
                        turnMode = "Linear",
                        turnInstant = false,
                        useParentTarget = false,
                        useRootTarget = false,
                        targetRootUnit = false,
                        mountAngles = {
                            left = 0,
                            right = 0,
                            up = 0,
                            down = 0,
                        },
                        weaponData = {
                            weaponType = "LAUNCHER",
                            alwaysfire = true,
                            magdump = false,
                            necrofire = true,
                            active = false,
                            oneuse = false,
                            exemptFromRangeSanityChecks = false,
                            rangeInUnits = 0,
                            maximumAngleToTarget = 0,
                            unitsPerSecond = 5,
                            velocityStd = 1,
                            spreadDegrees = 1800,
                            spreadType = "RANDOM",
                            forceRaycastDirectlyToTarget = false,
                            lockTime = 0,
                            simultaniousObjectLimit = 0,
                            damageData = {
                                isNondamaging = false,
                                instances = 0,
                                damage = 0,
                                piercing = 0,
                                shred = 0,
                                heat = 0,
                                vulnerability = 0,
                                decloak = false,
                                targetingPriorityMultiplier = 0,
                                impulseForce = 0,
                            },
                            selfHealRatio = 0,
                            selfDamage = 0,
                            selfHeat = 0,
                            selfImpulseForce = 0,
                            isNonDecloaking = false,
                            dontFireBelowHealthFraction = 0,
                            resumeFireAboveHealthFraction = 0,
                            dontFireAboveHeatFraction = 0,
                            resumeFireBelowHeatFraction = 0,
                            rangeLimitWhenCloaked = 0,
                            dontFireWhenCloaked = false,
                            isResourceMiner = false,
                            isPiercing = false,
                            piercingThreshold = 0,
                            tractorHoldDistance = 0,
                            isAreaOfEffect = false,
                            aoeData = {
                                friendlyFire = false,
                                maximumDegrees = 0,
                                radiusOuter = 0,
                                radiusInner = 0,
                                waveSteps = 0,
                                waveSeconds = 0,
                            },
                            sfxID = 0,
                            SFXIntensity = 0,
                            sizeInUnits = 0,
                            lifetime = 0,
                            impactSize = 0,
                            impactDuration = 0,
                            disableImpactEffect = false,
                            disableImpactFlash = false,
                            impactColour = { 0, 0, 0, 0 },
                            impactFresnelStrength = 0,
                            disableImpactSizeVariance = false,
                            snapUnitDeathExplosionToImpactPosition = false,
                            impactEffectType = "EXPLOSION",
                            laserDescription = {
                                duration = 0,
                                opacity = 0,
                                diameter = 0,
                                offset = 0,
                                rotateZ = false,
                                rotateY = false,
                                rotateZUpdate = false,
                                rotateYUpdate = false,
                                noRescaleLength = 0,
                                noFade = false,
                                noShrink = false,
                            },
                            lasersPerShot = 0,
                            barrelCount = 0,
                            barrelSpacing = 0,
                            virtualBarrelOffset = { 0, 0, 0 },
                            barrelIndexCurrent = 0,
                            spawnID = 33010,
                            arrivalData = {
                                type = "NONE",
                                arrivalDuration = 0,
                                approachSpeed = 0,
                                keepDisabled = false,
                            },
                            checkForWaypoints = false,
                            ignoreRootVelocity = false,
                            setAutoWaypointTargetToWeaponTarget = false,
                            reloadAmount = 0,
                            secondsPerCycle = 9999,
                            secondsPerCycleCurrent = 0,
                            shotsPerCycle = 30,
                            shotsPerCycleCurrent = 30,
                            simultaniousShots = 30,
                            secondsPerShot = 0,
                            secondsPerShotCurrent = 0,
                        },
                        targeting = {
                            acquisition = {
                                type = "QUADTREE_ONLY",
                                isFriendly = false,
                                isResourceMiner = false,
                                acceptFirstValidTarget = false,
                                pauseIfHasTarget = false,
                                ignoreUncapturable = false,
                                ignoreNonHealRequester = false,
                                targetOnlySpecialType = 0,
                                secondsPerScan = 0,
                                ignoreFullHealth = false,
                                minimumHealth = 0,
                                minimumDistance = 0,
                                maximumDistance = 0.1,
                                maximumAngle = 0,
                                addedPreaimDistance = 0,
                                scoreForDistance = 1,
                                scoreForHealth = 0,
                                scoreForHealthCurrent = 0,
                                scoreForHealthCurrentMissing = 0,
                                scoreForHealthCurrentPercentage = 0,
                                scoreForArmour = 0,
                                scoreForArmourCurrent = 0,
                                scoreForAngle = 0,
                                scoreForMountAngle = 0,
                                perceivedHealthMax = 0,
                                perceivedHealthMin = 0,
                                perceivedArmourMax = 0,
                                perceivedArmourMin = 0,
                                perceivedDistanceMin = 0,
                                classMultMissile = 0,
                                classMultDrone = 0,
                                classMultLight = 0,
                                classMultMedium = 0,
                                classMultHeavy = 0,
                                classMultCapital = 0,
                                classMultTitan = 0,
                                shipMultiplier = 0,
                                structureMultiplier = 0,
                                keepTargetMultiplier = 0,
                                scoreBandingSize = 0,
                            },
                            tracking = {
                                workOnNullEntity = false,
                                positionPredictionType = "NONE",
                                predictionVelocityOveride = 0,
                                predictionAcceleration = 0,
                                doAimingComputation = false,
                                canInvalidateTarget = false,
                                invalidationDistance = 0,
                                invalidationAngle = 0,
                                invalidationVelocityHeadOn = 0,
                            },
                        },
                    },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.5,
        angularDamping = 0.5,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    health = {
        unitClass = "TITAN",
        health = 200000,
        health_regen_per_second = 75,
        max_regen_frac = 0,
        armour = 100,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0.2,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 30,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = true,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = true,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 3110,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0.5,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
