return {
    unitName = "turret_untres",
    unitDisplayName = "Untreskabreker",
    unitTooltip = "",
    unitBlurb = "Anti-Capital Artillery",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "K",
    picture = "1_12026_turret_untres.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012026,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 500,
        cost_energy = 250,
        cost_supply = 0,
        cost_time = 60,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Anti-Capital Artillery Turret</color>\nDesigned to target large sit-back threats.\n- Strong against Capitals / Heavies.\n- Poor against Lights / Mediums.",
        description = "Un Tres Kabreker. \nONE BARREL IMPALER.\n\nA modified planetary defence gun, oriented for Spancial combat. The range of it's heavy unobtanium slug is reduced significantly by the spancial environment, but it none the less is able to deliver deadly firepower at long range.\n\nThe pride of the Kontaalen people. The symbol of their survival in the wartorn Outer Frontier, and a terrifying threat to any Capital vessel that dares to enter it's firing envelope.\n\nIn Kontaal's fledgling hours, their home world of Rallio Pralga was invaded by the Indrosen. The vast capital vessels stretched the skies of Rallio Pralga's farm lands. The desperate colonists erected the grand artillery, but could not protect the whole world. Earthsoul Draves affixed to it multiple atmospheric burn engines, turning an Untreskabreker into the first Untresnafol. \n\nFleetmarshal Enexeo has repeatedly lobbied to replace the Untreskabreker with the experimental Korevnasor point-light heat artillery pieces. But has repeately been told by Fleetsoul Presell, that \"Unless the Korevnasor can outrange the Untreskabreker, it's not getting replaced.\"",
        weaponInfo = {
            { 1015034, 1, 1015030 },
        },
    },
    scale = 4,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    displayAreaRadius = 36,
    displayAreaColour = { 1, 0, 0, 0.25098 },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_structure_turret_untres/01_structure_turret_untres",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "untres",
            position = { 0, 0.349, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015034,
                turnSpeed = 5.729578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 25,
                    down = 28,
                },
            },
            parts = {
                {
                    name = "body",
                    mesh = "01_structure_turret_untres/01_structure_turret_untres_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
                {
                    name = "barrel",
                    position = { 0, 0, 0.554 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "laser_beam",
                    mesh = "cannonflash/cannonflash",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0.55474 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    weaponVisualConfig = {
                        laserColour = { 1, 0.632157, 0.47451, 1 },
                        intensity = 35,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "turretModel",
                    mesh = "01_ship_capital_untresnafol/01_ship_capital_untresnafol_solo_mk3",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_structure_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0.25, -0.09, 0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 0.5, 0.5 },
                },
                {
                    name = "model (4)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0.321, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.40454, 0.40454, 0.40454 },
                },
                {
                    name = "model (5)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0.346, 0.462 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.161399, 0.161399, 0.244752 },
                },
                {
                    name = "model (7)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0.346, 0.22 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.161399, 0.161399, 0.244752 },
                },
                {
                    name = "model (6)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0.354, -0.313 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.24898, 0.24898, 0.24898 },
                },
                {
                    name = "model (2)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0.25, -0.09, -0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 0.5, 0.5 },
                },
                {
                    name = "model (1)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { -0.25, -0.09, 0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 0.5, 0.5 },
                },
                {
                    name = "model (3)",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { -0.25, -0.09, -0.25 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5, 0.5, 0.5 },
                },
                {
                    name = "glow",
                    mesh = "01_structure_turret_untres/01_structure_turret_untres",
                    materials = { "01_MT_buildglow_4", "01_MT_buildglow_4", "01_MT_buildglow_4" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    parts = {
                        {
                            name = "body (1)",
                            mesh = "01_structure_turret_untres/01_structure_turret_untres_body",
                            materials = { "01_MT_buildglow_3", "01_MT_buildglow_3" },
                            position = { 0, 0.348999, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 1 },
                            turretBody = true,
                        },
                        {
                            name = "turretModel (1)",
                            mesh = "01_ship_capital_untresnafol/01_ship_capital_untresnafol_solo_mk3",
                            materials = { "01_MT_buildglow_4", "01_MT_buildglow_4", "01_MT_buildglow_4" },
                            position = { 0, 0.348999, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 1 },
                        },
                    },
                },
            },
        },
        {
            name = "colliders",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            parts = {
                {
                    name = "collider",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    physicsShape = {
                        shapeType = "Box",
                        center = { 0, -0.15, 0 },
                        size = { 1, 1, 0.442309 },
                        orientation = { 90, 0, 0 },
                        bevelRadius = 0.884619,
                        collisionResponse = "None",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
                {
                    name = "collider (1)",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    physicsShape = {
                        shapeType = "Capsule",
                        center = { 0, -0.03, 0 },
                        radius = 0.2,
                        height = 1,
                        orientation = { 90, 0, 0 },
                        collisionResponse = "None",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
            },
        },
        {
            name = "Aegis",
            mesh = "01_aegis_icosphere/01_aegis_icosphere",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    health = {
        unitClass = "CAPITAL",
        health = 10000,
        health_regen_per_second = 10,
        max_regen_frac = 0,
        armour = 20,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 1.2,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013023,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "OFFENCE",
        ring = { 0, 0 },
        rectangle = { 4, 4 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 3,
    },
}
