return {
    unitName = "titan_soulwarden_wing_left",
    unitDisplayName = "Soul Warden Wing Left",
    unitTooltip = "",
    unitBlurb = "",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_11029_titan_soulwarden_wing_left.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1011029,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "HIDDEN",
        requiredLevelForVisible = "2009",
        requiredLevelForDescription = "2009",
        tactical = "",
        description = "<color=red>[ WARNING ]</color>\nLittle to no recorded combat information. Tactical approximation:\n\n<color=yellow>Tactical</color>\n+ Mobile Fleet Factory\n+ Dominating Anti-Capital Armerments\n+ Excessive fleet support.\n+ Enormous.\n+ Unique\n\n\n[Halt's Note]\n\nSo. You know how the Kontaalen are a massive galactic nation with a war obsession? Yeah. Yeah.\n\nThis thing is serious, a proper war titan designed to single handedly dominate entire regions of the Spance. It is among the few reasons Crowe was willing to have peace with the Kontaalen for a time.\n\nNo one has dueled the Soul Warden, apart from Crowe's most elite commanders. And they don't win, they just survive. The Kontaalen don't let this thing out for nothing, and I assure you one of the fleetsouls are onboard.\n\nThere's rumors that there are three of these things. Personally, I hope that's just rumor.\n\nDO NOT, and I'm saying this against future me also. DO NOT, EVER, engage the Soul Warden without one hell of a good plan!",
        weaponInfo = {
            { 1015055, 6, 0 },
            { 1015035, 3, 0 },
            { 1015075, 1, 1015000 },
            { 1015076, 1, 0 },
        },
    },
    scale = 5,
    colliderDimensions = {
        widthMultiplier = 0.6,
        heightMultiplier = 0.5,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_hero_wesnett_soulwarden/01_titan_soulWarden_wing_left",
    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_teamColour" },
    parts = {
        {
            name = "Colliders",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 4.024276, 4.024276, 4.024276 },
            parts = {
                {
                    name = "left",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    physicsShape = {
                        shapeType = "Box",
                        center = { 0, 0, 0 },
                        size = { 0.155535, 0.099847, 0.253556 },
                        orientation = { 0, 0, 0 },
                        bevelRadius = 0.57,
                        collisionResponse = "None",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
            },
        },
        {
            name = "turret_thumper_right_top",
            position = { -0.270979, 0.145676, -0.026359 },
            rotation = { 0, 270, 0 },
            scale = { 0.100607, 0.100607, 0.100607 },
            weapon = {
                weaponID = 1015055,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 10,
                    right = 180,
                    up = 50,
                    down = 10,
                },
            },
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.25, 0.578341, 1, 1 },
                        intensity = 3.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                },
                {
                    name = "gun",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_gun",
                    materials = { "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "turret_thumper_right_top (1)",
            position = { -0.270979, 0.145676, -0.288541 },
            rotation = { 0, 270, 0 },
            scale = { 0.100607, 0.100607, 0.100607 },
            weapon = {
                weaponID = 1015055,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 10,
                    right = 180,
                    up = 50,
                    down = 10,
                },
            },
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.25, 0.578341, 1, 1 },
                        intensity = 3.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                },
                {
                    name = "gun",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_gun",
                    materials = { "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "turret_thumper_right_top (2)",
            position = { -0.270979, 0.145676, 0.243871 },
            rotation = { 0, 270, 0 },
            scale = { 0.100607, 0.100607, 0.100607 },
            weapon = {
                weaponID = 1015055,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 10,
                    right = 180,
                    up = 50,
                    down = 10,
                },
            },
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.25, 0.578341, 1, 1 },
                        intensity = 3.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                },
                {
                    name = "gun",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_gun",
                    materials = { "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "turret_thumper_right_top (3)",
            position = { -0.270979, -0.145676, -0.026359 },
            rotation = { 0, 270, 180 },
            scale = { 0.100607, 0.100607, 0.100607 },
            weapon = {
                weaponID = 1015055,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 10,
                    right = 180,
                    up = 50,
                    down = 10,
                },
            },
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.25, 0.578341, 1, 1 },
                        intensity = 3.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                },
                {
                    name = "gun",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_gun",
                    materials = { "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "turret_thumper_right_top (4)",
            position = { -0.270979, -0.145676, -0.288541 },
            rotation = { 0, 270, 180 },
            scale = { 0.100607, 0.100607, 0.100607 },
            weapon = {
                weaponID = 1015055,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 10,
                    right = 180,
                    up = 50,
                    down = 10,
                },
            },
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.25, 0.578341, 1, 1 },
                        intensity = 3.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                },
                {
                    name = "gun",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_gun",
                    materials = { "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "turret_thumper_right_top (5)",
            position = { -0.270979, -0.145676, 0.243871 },
            rotation = { 0, 270, 180 },
            scale = { 0.100607, 0.100607, 0.100607 },
            weapon = {
                weaponID = 1015055,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 10,
                    right = 180,
                    up = 50,
                    down = 10,
                },
            },
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.25, 0.578341, 1, 1 },
                        intensity = 3.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                },
                {
                    name = "gun",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_gun",
                    materials = { "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_medium_laser_ekudon/01_turret_ekudon_body",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0.000014, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "turret_striker",
            position = { -0.41046, 0, -0.024146 },
            rotation = { 0, 0, 90 },
            scale = { 0.201214, 0.201214, 0.201214 },
            weapon = {
                weaponID = 1015035,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 90,
                    down = 10,
                },
            },
            parts = {
                {
                    name = "turretModel",
                    mesh = "01_turret_pulseCannon/01_structure_T108_barrel",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_pulseCannon/01_structure_T108_body",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
                {
                    name = "Barrel",
                    position = { 0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "Barrel (1)",
                    position = { -0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.3, 0.604189, 1, 1 },
                        intensity = 3.25,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "laser_beam (1)",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { -0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.3, 0.604189, 1, 1 },
                        intensity = 3.25,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "turret_striker (1)",
            position = { -0.41046, 0, 0.243871 },
            rotation = { 0, 0, 90 },
            scale = { 0.201214, 0.201214, 0.201214 },
            weapon = {
                weaponID = 1015035,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 90,
                    down = 10,
                },
            },
            parts = {
                {
                    name = "turretModel",
                    mesh = "01_turret_pulseCannon/01_structure_T108_barrel",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_pulseCannon/01_structure_T108_body",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
                {
                    name = "Barrel",
                    position = { 0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "Barrel (1)",
                    position = { -0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.3, 0.604189, 1, 1 },
                        intensity = 3.25,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "laser_beam (1)",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { -0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.3, 0.604189, 1, 1 },
                        intensity = 3.25,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "turret_striker (2)",
            position = { -0.41046, 0, -0.289748 },
            rotation = { 0, 0, 90 },
            scale = { 0.201214, 0.201214, 0.201214 },
            weapon = {
                weaponID = 1015035,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 90,
                    down = 10,
                },
            },
            parts = {
                {
                    name = "turretModel",
                    mesh = "01_turret_pulseCannon/01_structure_T108_barrel",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_pulseCannon/01_structure_T108_body",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
                {
                    name = "Barrel",
                    position = { 0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "Barrel (1)",
                    position = { -0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.3, 0.604189, 1, 1 },
                        intensity = 3.25,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "laser_beam (1)",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { -0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.3, 0.604189, 1, 1 },
                        intensity = 3.25,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "Light Launchers",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            parts = {
                {
                    name = "Tolly Launcher Ridge A",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    weapon = {
                        weaponID = 1015075,
                        turnSpeed = 0,
                        turnMode = "Linear",
                        turnInstant = false,
                        useParentTarget = false,
                        useRootTarget = false,
                        targetRootUnit = false,
                        mountAngles = {
                            left = 0,
                            right = 0,
                            up = 0,
                            down = 0,
                        },
                    },
                    parts = {
                        {
                            name = "Launch Point (1)",
                            position = { 0.15601, 0.228619, 0.32488 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (2)",
                            position = { 0.0542, 0.2013, 0.32488 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (3)",
                            position = { -0.0494, 0.173599, 0.32488 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (4)",
                            position = { -0.1529, 0.145798, 0.32488 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (1)",
                            position = { 0.15601, 0.228619, 0.05588 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (2)",
                            position = { 0.0542, 0.2013, 0.05588 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (3)",
                            position = { -0.0494, 0.173599, 0.05588 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (4)",
                            position = { -0.1529, 0.145798, 0.05588 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (1)",
                            position = { 0.15601, 0.228619, -0.21612 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (2)",
                            position = { 0.0542, 0.2013, -0.21612 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (3)",
                            position = { -0.0494, 0.173599, -0.21612 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (4)",
                            position = { -0.1529, 0.145798, -0.21612 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                    },
                },
                {
                    name = "Kana Launcher Ridge B",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    weapon = {
                        weaponID = 1015076,
                        turnSpeed = 0,
                        turnMode = "Linear",
                        turnInstant = false,
                        useParentTarget = false,
                        useRootTarget = false,
                        targetRootUnit = false,
                        mountAngles = {
                            left = 0,
                            right = 0,
                            up = 0,
                            down = 0,
                        },
                    },
                    parts = {
                        {
                            name = "Launch Point (1)",
                            position = { 0.15601, 0.28392, 0.19018 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (2)",
                            position = { 0.0542, 0.256601, 0.19018 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (3)",
                            position = { -0.0494, 0.2289, 0.19018 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (4)",
                            position = { -0.1529, 0.201099, 0.19018 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (1)",
                            position = { 0.15601, 0.28392, -0.07882 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (2)",
                            position = { 0.0542, 0.256601, -0.07882 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (3)",
                            position = { -0.0494, 0.2289, -0.07882 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (4)",
                            position = { -0.1529, 0.201099, -0.07882 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (1)",
                            position = { 0.15601, 0.28392, -0.35082 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (2)",
                            position = { 0.0542, 0.256601, -0.35082 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (3)",
                            position = { -0.0494, 0.2289, -0.35082 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                        {
                            name = "Launch Point (4)",
                            position = { -0.1529, 0.201099, -0.35082 },
                            rotation = { 285, 270, 0 },
                            scale = { 0.2, 0.2, 0.2 },
                            barrel = true,
                        },
                    },
                },
            },
        },
        {
            name = "fireball",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.8, 0.8, 0.8 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "LAUNCHER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 2,
                    velocityStd = 1,
                    spreadDegrees = 1800,
                    spreadType = "RANDOM",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0,
                    lifetime = 0,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0,
                        opacity = 0,
                        diameter = 0,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 33011,
                    arrivalData = {
                        type = "NONE",
                        arrivalDuration = 0,
                        approachSpeed = 0,
                        keepDisabled = false,
                    },
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 9999,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 20,
                    shotsPerCycleCurrent = 20,
                    simultaniousShots = 20,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "fireball (1)",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.8, 0.8, 0.8 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "LAUNCHER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 5,
                    velocityStd = 1,
                    spreadDegrees = 1800,
                    spreadType = "RANDOM",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    isNonDecloaking = false,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    rangeLimitWhenCloaked = 0,
                    dontFireWhenCloaked = false,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0,
                    lifetime = 0,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0,
                        opacity = 0,
                        diameter = 0,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 33010,
                    arrivalData = {
                        type = "NONE",
                        arrivalDuration = 0,
                        approachSpeed = 0,
                        keepDisabled = false,
                    },
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 9999,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 20,
                    shotsPerCycleCurrent = 20,
                    simultaniousShots = 20,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        predictionAcceleration = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.5,
        angularDamping = 0.5,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    health = {
        unitClass = "TITAN",
        health = 150000,
        health_regen_per_second = 50,
        max_regen_frac = 0,
        armour = 45,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0.2,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 30,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = true,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = true,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 3110,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0.5,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
