return {
    unitName = "turret_cannon",
    unitDisplayName = "Striker Cannon",
    unitTooltip = "",
    unitBlurb = "Light Defence Turret",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "C",
    picture = "1_12002_turret_cannon.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012002,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 15,
        cost_energy = 5,
        cost_supply = 0,
        cost_time = 10,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Anti-Light Turret</color>\nDesigned to hold off early Light aggression.\n- Strong against Lights.\n- Decent against Mediums.\n- Poor against 20+ Armour.\n- Vulnerable to Artillery.",
        description = "- - -\nInfo:\n\nThe T108 defence turret, a reliable design used excessively throughout Kontaalen territory.\n\nFleetmarshal Jalia is credited with the \"inspiration\" of strapping a Tolly's gun to a turreted mount and over charging the range amplifiers. According to multiple engineers, the efficacy of the T(olly)101 was \"frustrating\" when compared to the preceeding PD58 defence spire. Thankfully, over multiple iterations the Tolly gun was replaced by a purpose-designed Point-Light dual cannon.",
        weaponInfo = {
            { 1015035, 1, 0 },
        },
    },
    scale = 1,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    displayAreaRadius = 9,
    displayAreaColour = { 1, 0, 0, 0.25098 },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_turret_pulseCannon/01_structure_T108",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamColour" },
    parts = {
        {
            name = "turret_beam",
            position = { 0, 0.327, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015035,
                turnSpeed = 57.29578,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 90,
                    down = 10,
                },
            },
            parts = {
                {
                    name = "turretModel",
                    mesh = "01_turret_pulseCannon/01_structure_T108_barrel",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "body",
                    mesh = "01_turret_pulseCannon/01_structure_T108_body",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
                {
                    name = "Barrel",
                    position = { 0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "Barrel (1)",
                    position = { -0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    barrel = true,
                },
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.3, 0.604189, 1, 1 },
                        intensity = 3.25,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "laser_beam (1)",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { -0.0593, 0, 0.4417 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.3, 0.604189, 1, 1 },
                        intensity = 3.25,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_aegis_icosphere/01_aegis_icosphere",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_small",
            mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
            materials = { "01_MT_BaseColour_structure_primary" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "glow",
                    mesh = "01_turret_pulseCannon/01_structure_T108",
                    materials = { "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    parts = {
                        {
                            name = "body (1)",
                            mesh = "01_turret_pulseCannon/01_structure_T108_body",
                            materials = { "01_MT_buildglow_1", "01_MT_buildglow_1" },
                            position = { 0, 0.326996, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 1 },
                            turretBody = true,
                        },
                        {
                            name = "turretModel (1)",
                            mesh = "01_turret_pulseCannon/01_structure_T108_barrel",
                            materials = { "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1" },
                            position = { 0, 0.326996, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 1, 1, 1 },
                        },
                    },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Sphere",
        center = { 0, 0, 0 },
        radius = 0.5,
        orientation = { 0, 0, 0 },
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "MEDIUM",
        health = 500,
        health_regen_per_second = 3,
        max_regen_frac = 0,
        armour = 10,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 1,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 1.2,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013021,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "DEFENCE",
        ring = { 0, 0 },
        rectangle = { 1, 1 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 1,
    },
}
