return {
    unitName = "yard_light",
    unitDisplayName = "Yard L1",
    unitTooltip = "",
    unitBlurb = "Light Shipyard",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "C",
    picture = "1_12001_yard_light.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012001,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 15,
        cost_energy = 0,
        cost_supply = 1,
        cost_time = 10,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "- - -\n\nThe Mk28 Yard L1's fabrication array and cohension deck can produce the entirety of Kontaal's 50m light vessel schematics - whether exotic or normal - in times unmatched by any counterpart.\n\nThe cohension deck of the Yard L1 was the prototype and basis for all ship yards in the Spance. Simply cohereing surrounding matter on to the attracting surface, and moulding it into whatever vessel is needed. It is both a staggering and now common technology only viable within the Spance.",
    },
    scale = 1,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_yard_light/01_yard_light",
    materials = { "01_MT_BaseColour_teamColour", "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_structure_secondary" },
    parts = {
        {
            name = "Vortex Cohesion Deck",
            mesh = "vortex Dome/vortex_dome_shell",
            materials = { "mt_vortex_dome_shell_cohesionDeck" },
            position = { 0, 0.2274, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.720634, -0.263464, 0.720634 },
            vortex = true,
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_yard_light_aegis/01_yard_light_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_small",
            mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
            materials = { "01_MT_BaseColour_structure_primary" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "glow",
                    mesh = "01_yard_light/01_yard_light",
                    materials = { "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2", "01_MT_buildglow_2" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
        {
            name = "Spawnpoint",
            position = { 0, 0.193, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            spawnerSpawnPoint = {
                code = 0,
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 1, 0.5, 1 },
        orientation = { 0, 0, 0 },
        bevelRadius = 0.5,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "MEDIUM",
        health = 500,
        health_regen_per_second = 3,
        max_regen_frac = 0,
        armour = 5,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 1,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013021,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "PRODUCTION",
        ring = { 0, 0 },
        rectangle = { 1, 1 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = true,
    spawner = {
        spawnOffset = { 0, 3, 0 },
        spawnOffsetHeightRandomisation = 1,
        endRotationUseStructureForward = false,
        noUnitGhost = false,
        usesToSelfdestruct = 0,
        simultaniousUnitLimit = 0,
        arrivalData = {
            type = "ARRIVE",
            arrivalDuration = 2,
            approachSpeed = 0.1,
            keepDisabled = false,
        },
    },
    spawnerCapacity = {
        current = 0,
    },
    spawnItems = {
        {
            id = 1011000,
            spawnTime = 15,
            spawnTimeStart = 15,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011021,
            spawnTime = 15,
            spawnTimeStart = 15,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011007,
            spawnTime = 15,
            spawnTimeStart = 15,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011006,
            spawnTime = 30,
            spawnTimeStart = 30,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
        {
            id = 1011017,
            spawnTime = 30,
            spawnTimeStart = 30,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = false,
            heatPercentage = 0,
            techID = 0,
        },
    },
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
