return {
    unitName = "turret_howitzer",
    unitDisplayName = "Pulse Howitzer",
    unitTooltip = "",
    unitBlurb = "Heavy Destroyer Turret",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "H",
    picture = "1_12008_turret_howitzer.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012008,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 150,
        cost_energy = 50,
        cost_supply = 0,
        cost_time = 20,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Anti-Armour Turret</color>\nDesigned to hold off large targets.\n- Strong against Heavies.\n- Decent against Mediums.\n- Poor against Lights.",
        description = "- - -\nInfo:\n\nThe PDH 85 Howitzer Spire is a common and powerful defence spire, deployed plentifully throught the Spance. Used to fortify bases against medium-scale assaults and large asteroids.\n\nFleetforger Roniel has upon many occasions stated that \"if we just made a bigger one and strapped it to an Ekudon we'd've dominated the Spance already.\" He has likewise been reminded multiple times that the Ekudon and PDH85 Howitzer Spire share the exact same ( upscaled ) weapon ALREADY.",
        weaponInfo = {
            { 1015012, 1, 0 },
        },
    },
    scale = 2,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    displayAreaRadius = 15,
    displayAreaColour = { 1, 0, 0, 0.25098 },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_turretbase_pulseHowitser/01_turretbase_pulseHowitser",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "turret_beam",
            position = { 0, 0.502, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015012,
                turnSpeed = 28.64789,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 180,
                    right = 180,
                    up = 90,
                    down = 20,
                },
            },
            parts = {
                {
                    name = "laser_beam",
                    mesh = "coilbeam/coilbeam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0.118 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.0384, 0.0384, 0.0384 },
                    weaponVisualConfig = {
                        laserColour = { 1, 0.564136, 0.25, 1 },
                        intensity = 3,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "barrel",
                    mesh = "01_turret_pulseHowitser/01_pulseHowitser_barrel",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5696, 0.5696, 0.5696 },
                },
                {
                    name = "body",
                    mesh = "01_turret_pulseHowitser/01_pulseHowitser_body",
                    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.5696, 0.5696, 0.5696 },
                    turretBody = true,
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_turretbase_pulseHowitser_aegis/01_turretbase_pulseHowitser_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0.164, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_turretbase_pulseHowitser/01_turretbase_pulseHowitser",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, -0.164, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    parts = {
                        {
                            name = "barrel (1)",
                            mesh = "01_turret_pulseHowitser/01_pulseHowitser_barrel",
                            materials = { "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_2" },
                            position = { 0, 0.501999, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.5696, 0.5696, 0.5696 },
                        },
                        {
                            name = "body (1)",
                            mesh = "01_turret_pulseHowitser/01_pulseHowitser_body",
                            materials = { "01_MT_buildglow_1", "01_MT_buildglow_1" },
                            position = { 0, 0.501999, 0 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.5696, 0.5696, 0.5696 },
                            turretBody = true,
                        },
                    },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 1.1, 0.9, 1.1 },
        orientation = { 0, 0, 0 },
        bevelRadius = 0.9,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "HEAVY",
        health = 3000,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 45,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 2.5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 1.2,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "DEFENCE",
        ring = { 0, 0 },
        rectangle = { 2, 2 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = false,
        tier = 2,
    },
}
