return {
    unitName = "turret_beam",
    unitDisplayName = "Beam Spire",
    unitTooltip = "",
    unitBlurb = "Heavy Point Defence",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "B",
    picture = "1_12007_turret_beam.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012007,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 100,
        cost_energy = 25,
        cost_supply = 0,
        cost_time = 20,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Point Defence Turret</color>\nDesigned to hold off missile sit-backers, and drone swarms.\n- Strong against Missiles / Drones.\n- Decent against Lights.\n- Poor against 10+ Armour.\n- Vulnerable to Artillery.",
        description = "- - -\nInfo:\n\nThe PDPLA Mk2 Beam Spire is among Kontaal's oldest and most refined defence structures. Utilised plentifully throughout the Spance to protect against asteroid-storms and drone-swarms.\n\nInternally, the Beam Spire is an extremely complex refraction system that allow it's 6 beam emitters to be routed through the central refraction-core in any direction necissary. Sadly, the limitation of this ancient design is that the beams cannot have any armour-piercing potential less they destroy the Beam Spire's refraction core.\n\n\nFleetsoul Presell once used an encircling sphere of over 50 beamspires to utterly obliterate a Vaalkorei onslaught numbering over 100,000 heavy-assault drones deployed from 20 Eyries. The total devestation resulted in 100,000 tiny husks orbiting the planet of Tryo-go ripping through the Vaalkorei installations and forces posted there. While the beam Spires themselves effortlessly burned up the debris headed to them.",
        weaponInfo = {
            { 1015011, 6, 0 },
        },
    },
    scale = 2,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    displayAreaRadius = 10,
    displayAreaColour = { 1, 0, 0, 0.25098 },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_turret_beamSpire/01_turret_beamspire",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_PointLightGlow_Low", "01_MT_BaseColour_structure_secondary" },
    parts = {
        {
            name = "unitBubble(Clone)",
            mesh = "01_turret_beamSpire/01_turret_beamspire_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "turret_beam up",
            position = { 0, 0.730202, 0 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015011,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = true,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 130,
                    right = 130,
                    up = 130,
                    down = 130,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "taperbeam/taperbeam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.06, 0.06, 0.06 },
                    weaponVisualConfig = {
                        laserColour = { 0.34902, 0.635294, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "turret_beam front",
            position = { 0, 0.670197, 0.06 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015011,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = true,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 130,
                    right = 130,
                    up = 130,
                    down = 130,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "taperbeam/taperbeam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.06, 0.06, 0.06 },
                    weaponVisualConfig = {
                        laserColour = { 0.34902, 0.635294, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "turret_beam back",
            position = { 0, 0.670197, -0.06 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015011,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = true,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 130,
                    right = 130,
                    up = 130,
                    down = 130,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "taperbeam/taperbeam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.06, 0.06, 0.06 },
                    weaponVisualConfig = {
                        laserColour = { 0.34902, 0.635294, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "turret_beam left",
            position = { -0.06, 0.670197, 0 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015011,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = true,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 130,
                    right = 130,
                    up = 130,
                    down = 130,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "taperbeam/taperbeam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.06, 0.06, 0.06 },
                    weaponVisualConfig = {
                        laserColour = { 0.34902, 0.635294, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "turret_beam right",
            position = { 0.06, 0.670197, 0 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015011,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = true,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 130,
                    right = 130,
                    up = 130,
                    down = 130,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "taperbeam/taperbeam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.06, 0.06, 0.06 },
                    weaponVisualConfig = {
                        laserColour = { 0.34902, 0.635294, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "turret_beam core",
            position = { 0, 0.670197, 0 },
            rotation = { 270, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015011,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = true,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 130,
                    right = 130,
                    up = 130,
                    down = 130,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "taperbeam/taperbeam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.06, 0.06, 0.06 },
                    weaponVisualConfig = {
                        laserColour = { 0.34902, 0.635294, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0.3, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_turret_beamSpire/01_turret_beamspire",
                    materials = { "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3", "01_MT_buildglow_3" },
                    position = { 0, -0.3, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Sphere",
        center = { 0, 0, 0 },
        radius = 0.5,
        orientation = { 90, 0, 0 },
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "HEAVY",
        health = 3000,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 20,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 2.5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 1.2,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "DEFENCE",
        ring = { 0, 0 },
        rectangle = { 2, 2 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 2,
    },
}
