return {
    unitName = "bullet_shredder_slug",
    unitDisplayName = "Shredder Slug",
    unitTooltip = "",
    unitBlurb = "",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_14007_bullet_shredder_slug.png",
    controllable = false,
    unselectable = true,
    untargetable = true,
    unhittable = true,
    data = {
        typeID = 1014007,
        factionID = 101,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "0",
        requiredLevelForDescription = "",
        tactical = "",
        description = "",
        weaponInfo = {
            { 1015028, 1, 0 },
        },
    },
    scale = 0.13,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "bullet_shredder/01_bullet_shredder",
    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow" },
    parts = {
        {
            name = "warhead",
            position = { 0, 0, -0.65 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 1015028,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
            scaleModifier = true,
        },
    },
    unitCore = true,
    health = {
        unitClass = "NONE",
        health = 1,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 0,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0.2,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 1.71875,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
