return {
    unitName = "yard_mining",
    unitDisplayName = "Refinery M6",
    unitTooltip = "Supports one Jeren mining vessel.\nIgnores <color=#00ffff>Waypoints</color>.",
    unitBlurb = "Dedicated Mining Gantry",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "B",
    picture = "1_12040_yard_mining.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012040,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 50,
        cost_energy = 50,
        cost_supply = 4,
        cost_time = 30,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "- <color=green>+2 Matter</color> per second from mining.\n- Supports one Jeren miner.",
        description = "- - -\nInfo\n\nA dedicated refinery-dock able to crack hardened spancial materials into useful matter elements, and construct it's own Jeren mining vessel which will seek out rich deposits.\n\nThe Jeren and M6 both host ports for small rapid-transit material hauler drones known as Longdonkeys. Much like the many invisible construction drones of the Platforms, these drones are \"cloaked\", running on low power, dumb systems that allow them to traverse between the Jeren and Refinery without being threatened or even seen. Though this is only barely possible by using the most bare bones of AB navigation systems.\n\nOriginally, the Jeren was built from the Yard M4 and hosted it's own micro-refinery and logistics drones allowing it to operate independently of a refinery structure. However, this design demanded horrible tradeoffs in overall individual efficacy. As such the RM6 was deployed.\n\nSome have asked why the M6 is unable to support multiple Jerens, the answer is rather simple. The logistical support profile of a mining craft is such that ",
    },
    scale = 3,
    colliderDimensions = {
        widthMultiplier = 0.66,
        heightMultiplier = 0.66,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_yard_mining/01_yard_mining",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_teamColour" },
    parts = {
        {
            name = "Vortex Cohesion Deck",
            mesh = "vortex Dome/vortex_dome_shell",
            materials = { "mt_vortex_dome_shell_cohesionDeck" },
            position = { 0, 0.0683, 0.1209 },
            rotation = { 0, 0, 0 },
            scale = { 0.464601, -0.253666, 0.56507 },
            vortex = true,
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_yard_medium_aegis/01_yard_medium_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 0.68389, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "Construction Effects",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "glow",
                    mesh = "01_yard_mining/01_yard_mining",
                    materials = { "01_MT_buildglow_4", "01_MT_buildglow_4", "01_MT_buildglow_4" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "01_structure_prop_scafold_small",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0.1666, 0, -0.333 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.33, 0.33, 0.33 },
                },
                {
                    name = "01_structure_prop_scafold_small",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_small",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { -0.1666, 0, -0.333 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.33, 0.33, 0.33 },
                },
                {
                    name = "01_structure_prop_scafold_medium",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    parts = {
                        {
                            name = "model",
                            mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                            materials = { "01_MT_BaseColour_structure_primary" },
                            position = { 0, 0, 0.166666 },
                            rotation = { 0, 0, 0 },
                            scale = { 0.66, 0.3333, 0.66 },
                        },
                    },
                },
            },
        },
        {
            name = "Spawnpoint",
            position = { 0, 0.0284, 0.1253 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            spawnerSpawnPoint = {
                code = 0,
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 0.7, 0.35, 1.05 },
        orientation = { 0, 0, 0 },
        bevelRadius = 0.6,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "HEAVY",
        health = 2500,
        health_regen_per_second = 10,
        max_regen_frac = 0,
        armour = 5,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 2,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013022,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "PRODUCTION",
        ring = { 0, 0 },
        rectangle = { 2, 3 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = true,
    spawner = {
        spawnOffset = { 0, 3, 0.2 },
        spawnOffsetHeightRandomisation = 1,
        endRotationUseStructureForward = false,
        noUnitGhost = false,
        usesToSelfdestruct = 0,
        simultaniousUnitLimit = 1,
        arrivalData = {
            type = "ARRIVE",
            arrivalDuration = 3,
            approachSpeed = 0.2,
            keepDisabled = false,
        },
    },
    spawnerCapacity = {
        current = 0,
    },
    spawnItems = {
        {
            id = 1011019,
            spawnTime = 30,
            spawnTimeStart = -1,
            spawnPointCode = 0,
            spawnVelocity = 0,
            ignoreWaypoints = true,
            heatPercentage = 0,
            techID = 0,
        },
    },
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
