return {
    unitName = "generator_energy_3x3",
    unitDisplayName = "Graviton Engine",
    unitTooltip = "",
    unitBlurb = "Advanced <color=#00ffff>Energy</color> generator.",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "G",
    picture = "1_12004_generator_energy_3x3.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 1012004,
        factionID = 101,
        macroType = "FALSE",
        cost_matter = 250,
        cost_energy = 50,
        cost_supply = 10,
        cost_time = 45,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "- <color=red>Explodes violently when destroyed.</color>",
        description = "- - -\nInfo:\n\nWhile fusion and fission still stand the test of time, the ancient art of the wind turbine has reemerged to a modern world not at all ready for it's raw terrifying efficacy.\n\nThe Graviton Engine, as the turbines before it, is designed to exploit the motion of the environment around it. In this case, the Spance's ambient pulsing and wind-like gravity. The graviton core is quite literally spun by the Spance, generating serious energy output and dumping it into the connected energy grid.\n\nYou may ask why the Vaalkorei do not also utilise Kontaalen graviton engines, if they are such a \"simple concept\". To which the answer is simple. It isn't simple.\n\nThe precise engineering requirements to facilitate a graviton engine demand a significant number of tradeoffs all payed in the hair of frustrated engineers. To say nothing of the omnipresent danger of the core deciding to deshackel itself from this mortal coil and turn into a burning steel ball sent hurtling into a command center like a very expensive Strix torpedo with an odd sense of humor.\n\n\nIsak Yuliaprento invented the Graviton Engine's core concepts centuries ago. Yet unlike many of the other exotic technologies he created for Kontaal, the Graviton would only find use long after his death.",
    },
    scale = 3,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_structure_generator_energy/01_generator_energy",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_structure_secondary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_energyGlow" },
    parts = {
        {
            name = "piston",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            piston = {
                localDistanceUp = 0.006,
                direction = "UpAndDown",
                startProgressFraction = 0.25,
                duration = 0.5,
            },
            parts = {
                {
                    name = "rotatorpiston",
                    position = { 0, 0, 0 },
                    rotation = { 90, 0, 0 },
                    scale = { 1, 1, 1 },
                    rotate = {
                        timeStepSeconds = 0,
                        degreeRotationPerSecond = { 0, 0, 90 },
                    },
                    piston = {
                        localDistanceUp = 0.002,
                        direction = "UpAndDown",
                        startProgressFraction = 0.25,
                        duration = 0.1,
                    },
                    parts = {
                        {
                            name = "Core",
                            mesh = "01_structure_generator_energy/01_generator_energy_core",
                            materials = { "01_MT_BaseColour_energyGlow" },
                            position = { 0, 0, 0 },
                            rotation = { 270, 0, 0 },
                            scale = { 1, 1, 1 },
                            rotate = {
                                timeStepSeconds = 0,
                                degreeRotationPerSecond = { 30, 30, 90 },
                            },
                            piston = {
                                localDistanceUp = 0.003,
                                direction = "UpAndDown",
                                startProgressFraction = 0.25,
                                duration = 0.5,
                            },
                        },
                    },
                },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_structure_generator_energy_aegis/01_generator_energy_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            aegisVisual = true,
        },
        {
            name = "01_structure_prop_scafold_medium",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 0.4, 1 },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            destroyOnConstructionComplete = true,
            parts = {
                {
                    name = "model",
                    mesh = "01_structure_prop_scafolds/01_structure_prop_scafold_medium",
                    materials = { "01_MT_BaseColour_structure_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "glow",
                    mesh = "01_structure_generator_energy/01_generator_energy",
                    materials = { "01_MT_buildglow_4", "01_MT_buildglow_4", "01_MT_buildglow_4", "01_MT_buildglow_4" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 2.5, 1 },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 0.95, 0.3, 0.95 },
        orientation = { 0, 0, 0 },
        bevelRadius = 0.5,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "HEAVY",
        health = 5000,
        health_regen_per_second = 5,
        max_regen_frac = 0,
        armour = 10,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 4,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        lifetimeStd = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 4,
        flashSizeOverride = 0,
        forceShockwave = true,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = true,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 1013023,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "ECONOMY",
        ring = { 0, 0 },
        rectangle = { 3, 3 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = true,
    resourceGeneration = {
        matter = 0,
        energy = 5,
        phase = 0,
    },
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
    rogueDiveInfo = {
        inRogueDive = true,
        tier = 2,
    },
}
