return {
    id = "01_material_plasma_lantra",
    shader = "Universal Render Pipeline/Unlit",
    keywords = { "_SURFACE_TYPE_TRANSPARENT", "_EMISSION" },
    renderQueue = 3000,
    properties = {
        _AddPrecomputedVelocity = 0,
        _AlphaClip = 0,
        _AlphaToMask = 0,
        _BaseColor = { 0.354217, 0.33, 1, 0.05098 },
        _Blend = 0,
        _BlendOp = 0,
        _Color = { 0.354217, 0.33, 1, 0.05098 },
        _Cull = 2,
        _Cutoff = 0.5,
        _DstBlend = 10,
        _DstBlendAlpha = 10,
        _QueueOffset = 0,
        _SampleGI = 0,
        _SrcBlend = 5,
        _SrcBlendAlpha = 1,
        _Surface = 1,
        _XRMotionVectorsPass = 1,
        _ZWrite = 0,
    },
}
