return {
    id = "mt_vortex_dome_shell_cohesionDeck",
    shader = "Shader Graphs/VortexUnlit_DoubleSided",
    properties = {
        _Center = { 0.5, 0.5, 0, 0 },
        _Color = { 0.396226, 0.338801, 0.238483, 1 },
        _Direction = 1,
        _FadeOuter = 0.391,
        _FadeSoftness = 0.113,
        _FalloffInner = 0,
        _FalloffOuter = 0.272,
        _InvRStrength = 0,
        _MainTex = { texture = "Textures/noise_10_vortex.png" },
        _NoiseSpeed = { 0, 0, 0, 0 },
        _NoiseTiling = { 2, 2, 0, 0 },
        _Opacity = 1,
        _QueueControl = 0,
        _QueueOffset = 0,
        _SpinSpeed = -0.2,
        _Twist = 2.1,
        Opacity = 1,
    },
}
